### ISSUE TITLE
Error creating new positions

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#100]
The following error message is displayed in attempt to create a new position for Team Member, Enterprise Integration

A position cannot be hierarchically be linked to its subordinate.

Note that the new position was assigned level A5 and was to be linked to a Position on level A4 (Team Lead, EEnterprise Integration)

Please urgently treat as there are about 25 new positions to be created for new hires.

**Comment by Mandiklopper** [comment]
https://senseable.co.za/scp/tickets.php?id=209 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
Mandi looked into this. The Levels cleared on Standard Jobs and this did show previously. Also the sequencing on the Position codes are incorrect. Should be 5 and not 4.

**Comment by Mandiklopper** [comment]
@roberteta 
These positions are causing the issue to add the functional reports to on the positions.  These positions are reporting to themselves?  Once you correct this on the system you will not get the error anymore:

Position Code	         Hierarchical Sup L1
J0018009900434	J0018009900434
J0018056900433	J0018056900433
J0018059400428	J0018059400428
J0146029100032	J0146029100032
J0211017001957	J0211017001957
J0211018001931	J0211018001931
J0211023501948	J0211023501948
J0211057701924	J0211057701924
J0211060501835	J0211060501835
J0018026600430	J0018026600430
J0018037500423	J0018037500423
J0018041100457	J0018041100457
J0379041101468	J0018041102030
J0097019500046	J0097019500046
J0505003700008	J0505003700008
J0523099900009	J0523099900009
J0024099900004	J0024099900004
J0724047200007	J0724047200007

**Comment by jayekwueme** [comment]
Hello @Mandiklopper , 

I have re-mapped the indicated Positions and I have also done an export to identify positions without a functional report line and mapped all excluding the GMD but error message still persists when I try to create a new position.

![image](https://user-images.githubusercontent.com/29643618/33515188-e574f56c-d75f-11e7-8ec0-0175839037e7.png)

**Comment by Mandiklopper** [comment]
Mandi to look into this.

**Comment by Mandiklopper** [comment]
Reassigned on Senseable to JW to look at the error.

**Comment by Mandiklopper** [comment]
Solved.  Please retest.
