### ISSUE TITLE
Staff Movement Approver - GHHR showing as HRBP Team Lead 

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#101]
Please look into Redeployment request for A00255. 

Approver is showing as HRBP Team Lead
Approver Name is showing as Patricia Aderibigbe

Regards

**Comment by Mandiklopper** [comment]
@roberteta I cannot see a staff movement transaction for A00255.

**Comment by roberteta** [comment]
@ Mandi,

Sorry it is A00225 - Enitan Ayandokun

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=214 - Logged on Senseable not yet assigned

**Comment by Mandiklopper** [comment]
This redeployment was captured on X3 and the rule is that the supervisor of the user that created it on X3 is the HRBP.
Transaction captured by NGOKO, employee id is A03890, and supervisor A23364 (Patricia).
