### ISSUE TITLE
Notification message for Promotion Staff Movement

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#104]
The notification below was sent out for a Promotion Staff Movement transaction;

From: PeopleConnect@ubagroup.com [mailto:PeopleConnect@ubagroup.com] 
Sent: Monday, December 4, 2017 9:17 AM
To: Okafor, Ugochi <Ugochi.Okafor@ubagroup.com>
Cc: Owoseni, Oyebola <oyebola.owoseni@ubagroup.com>
Subject: Staff movement A24217 - Olanike Ayandele

Dear Ugochi Okafor,

The following staff movement transaction requires your approval:

EMPLOYEE ID: A24217
EMPLOYEE: Olanike Ayandele

CURRENT JOB DETAILS:
===================
DEPARTMENT/BRANCH: 51A Adeniyi Jones Street Ikeja (BR196)
LOCATION: 51A Adeniyi Jones, Ikeja, Lagos (0584)
JOB TITLE: Funds Transfer Officer

SUPERVISOR:  

STAFF MOVEMENT DETAILS:
======================
DEPARTMENT/BRANCH: 51A Adeniyi Jones Street Ikeja (BR196)
LOCATION: 51A Adeniyi Jones, Ikeja, Lagos (0584)
JOB TITLE: Funds Transfer Officer
SUPERVISOR:  

EFFECTIVE DATE: Thursday, 12 OCT 2017

Thank you.

Human Capital Management

There is no indication of the Grade, which is the main element changed in a propotion transaction.

Please modify the notification as follows;

1. Include 'Grade' in the Current Job Details section
2. Include 'New Grade' in the Staff Movement Details section
3. The opening statement should be 'The following promotion  transaction requires your approval'

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=215 - Logged on senseable not yet assigned.

**Comment by janwvjaarsveld** [comment]
Stale ticket. Please re-open if this is still an issue
