### ISSUE TITLE
HMO not defaulting for New Hire after Onboarding

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#107]
The HMO linked to the grade of new hires is not defaulted to the Employee (Civil Status tab) or Employment Contract (Health Information tab)  of these staff.

Please look into this as this will affect their ability to select hospitals via ESS

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=216 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
Closed by JW
