### ISSUE TITLE
Commendation letter and notification

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/People-Connect#110]
Please  delete the statement about 5 marks appraisal score in the notification and letter for commendation.  Commendation no longer has appraisal impact.

**Comment by Mandiklopper** [comment]
https://senseable.co.za/scp/tickets.php?id=219 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
@Adebukola this is not on the message or letter. Please check if entered on the Final commendation detail.

**Comment by janwvjaarsveld** [comment]
Stale ticket. Please re-open if this is still an issue
