### ISSUE TITLE
RELIEF ASSIGNMENT ERROR MESSAGE

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#113]
The attached contains the error message when trying to initiate  a relief assignment for A07355 from the Single processing screen

Error Message - FIELD ERROR  Employee ID
001 - You cannot access this service

**Comment by Mandiklopper** [comment]
@roberteta who tried to initiate the request?

**Comment by roberteta** [comment]
HRBP Team Member - A15774

**Comment by Mandiklopper** [comment]
@jwvjaar please look into this or has this been sorted?

**Comment by jwvjaar** [comment]
Same as #158.
