### ISSUE TITLE
WF: Sick leave - Notification

### ISSUE THREAD

**Issue by MartinKruger** [Mandiklopper/People-Connect#116]
[Senseable Ticket #212](https://senseable.co.za/scp/tickets.php?id=85&a=edit)

- Email notification in respect of approve sick leave should contain leave duration and other details such as impact on salary (e.g. full pay /half pay) where applicable.

- Salary impact: write generic shortened note describing policy (not specific to employee)

**Comment by P1errevanZyl** [comment]
Please supply the content of the policy to add it to the

**Comment by MartinKruger** [comment]
Your pay might be impacted as follows:
If you have been employed more than ten years, the first six months will be with full pay, the next six months with half pay and thereafter with no pay.
If you have been employed more than five years, the first five months will be with full pay, the next five months with half pay and thereafter with no pay.
If you have been employed more than two years, the first four months will be with full pay, the next five months with half pay and thereafter with no pay.
If you have been employed more than six months, the first two months will be with full pay, the next two months with half pay and thereafter with no pay.
If you have been employed less than six months, the first month will be with full pay, the next month with half pay and thereafter with no pay.

**Comment by MartinKruger** [comment]
For Leave of Absence, use the following:

You will receive no pay for the duration of this transaction.

**Comment by P1errevanZyl** [comment]
Made changes to XDCGFYI workflow

Patch 201801301306PIVAN

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Email notification with salary impact | Passed | Works as expected, when leave is approved an email notification goes through the workflow and when employee gets email notification of approved leave it also states the impact of salary.
