### ISSUE TITLE
WF: Staff movement notification

### ISSUE THREAD

**Issue by MartinKruger** [Mandiklopper/People-Connect#119]
[Senseable Ticket #240](https://senseable.co.za/scp/tickets.php?id=113)
**Robert Eta posted 07 Nov 17 @ 17:48** 
See redeployment notification received none of stakeholder i.e. receiving and releasing supervisors, payroll, etc.

Refer to email print screen of notification sent out.

**Comment by MartinKruger** [comment]
Jan Willem van Jaarsveld posted 09 Nov 17 @ 14:11 Ticket Assigned to Mandi Klopper
Staff, HRBP member, HRBP team lead, receiving and releasing supervisors and payroll will now be copied in the same email. However, the stakeholder group for Payroll must be loaded

**Comment by MartinKruger** [comment]
Mandi Klopper posted 13 Nov 17 @ 10:24 
Message from Robert:

There is no payroll mailing group currently. Payrollvalidation@ubagroup.com is for GSS-HCM and other staff that have worked on payroll before now.

JW to confirm if this is what is needed.

**Comment by MartinKruger** [comment]
Mandi Klopper posted 14 Nov 17 @ 10:37 

See redeployment notification received none of stakeholder i.e. receiving and releasing supervisors, payroll, etc.

See redeployment notification received none of stakeholder i.e. receiving and releasing supervisors, payroll, etc.

Refer to email print screen of notification sent out.

Refer to email print screen of notification sent out.

Look into this as well please: The notification mail for staff movement items awaiting approval of the HRBP Team Lead should copy the initiator of the request.

**Comment by MartinKruger** [comment]
Mandi Klopper posted 14 Nov 17 @ 10:39 Ticket Assigned to Jan Willem van Jaarsveld
Please look into this as well when you complete this task.

**Comment by MartinKruger** [comment]
Jan Willem van Jaarsveld posted 14 Nov 17 @ 10:53 
Initiator is now copied in.

**Comment by MartinKruger** [comment]
Mandi Klopper posted 22 Nov 17 @ 10:09 
Re-opened this ticket. Mandi did set up the stakeholders as instructed:

Message from Robert:
Only HRBP Team Member, Team Lead and Supervisors (Releasing and Receiving) were copied. Other stakeholders including payroll validation were not copied.

**Comment by MartinKruger** [comment]
Jan Willem van Jaarsveld posted 22 Nov 17 @ 12:32 Status Changed
Did the stakeholders not receive an email, or is this just based on the fact that they did not show in the workflow monitor?

**Comment by MartinKruger** [comment]
Mandi Klopper posted 23 Nov 17 @ 09:00 
@roberteta this will not show on the workflow monitor. This is still in progress as this is a custom development that the Dev team are working on.
In the example mail Payroll validation were included the cc line. Which other stakeholders are you referring to?

**Comment by MartinKruger** [comment]
Mandi Klopper posted 30 Nov 17 @ 08:11 
Message from Robert:

Hello Mandi,

The following stakeholders are not getting the staff movement notifications;

• 2nd level supervisors (both releasing and accepting)
• Branch Managers(BM) for branch staff

This is based on review of sample email notifications sent out. See sample below

From: PeopleConnect
Sent: Monday, November 27, 2017 5:36 PM
To: Abdulganiyu, Bashir bashir.abdulganiyu@ubagroup.com
Cc: Oyewale, Abdulrasheed abdulrasheed.oyewale@ubagroup.com; Jamgbadi, Kayode kayode.jamgbadi@ubagroup.com; Abdul, Musa Musa.Abdul@ubagroup.com; Abbagana, Zainab zainab.abbagana@ubagroup.com; Payrollvalidation Payrollvalidation@ubagroup.com; User_Admin HO user_admin.ho@ubagroup.com; Mohammed, Mistura mistura.mohammed@ubagroup.com; Akinpelu, Comfort comfort.akinpelu@ubagroup.com; Adeyemi, Elisha elisha.adeyemi@ubagroup.com; Abdulkareem, Ahmed ahmed.abdulkareem@ubagroup.com; Sagay, Israel israel.sagay@ubagroup.com; Adeshina, Babajide babajide.adeshina@ubagroup.com; Are, Olasunkanmi Olasunkanmi.Are@ubagroup.com; ITCARE ITCARE@ubagroup.com; Oprisk Mgt Team opriskmgtteam@ubagroup.com; ConfirmationTeam ConfirmationTeam@ubagroup.com; Recordsteam recordsteam@ubagroup.com; Isioma-Nwaligbe, Soso soso.isioma-nwaligbe@ubagroup.com; UBAAcademy ubaacademy@ubagroup.com; Seidu, Christy Christy.Seidu@ubagroup.com; Chuks-Ngwu, Christie christie.chuks-ngwu@ubagroup.com
Subject: Relief Assignment A09630 - Abdulganiyu Bashir

Dear Abdulganiyu Bashir,

We are pleased to inform you of your Relief Assignment.Please find the details below:

DEPARTMENT/BRANCH: CMC/ZPC Gombe (BR381)
LOCATION: Biu Road ,Gombe (0303)
NEW JOB TITLE: Head Cash Management Center
NEW SUPERVISOR: Abdulrasheed Oyewale
EFFECTIVE DATE: Wednesday, 22 NOV 2017
COMPLETION DATE: Sunday, 03 DEC 2017

PREVIOUS SOL ID: 0303
PREVIOUS JOB TITLE: Cash Officer

You are expected to hand-over to the next line officer or your supervisor and report to your new supervisor on the Effective Date.
Please note that failure to resume at your new location on the effective date will amount to policy infraction.
We wish you the best in your new assignment.

Thank you.

Human Capital Management

**Comment by Mandiklopper** [comment]
Duplicate See #2
