### ISSUE TITLE
INCORRECT GRADE

### ISSUE THREAD

**Issue by bldre03** [Mandiklopper/People-Connect#122]
Dear Mandi,

Kindly assist to update the grade for staff in the attached screenshot.

Incorrect Grade - ABO ; Correct Grade - SBO.

![grade update for_a04260_okhiria gladys](https://user-images.githubusercontent.com/33657390/33768446-5dad7692-dc26-11e7-9794-cf786d4b434e.png)

Regards,

**Comment by Mandiklopper** [comment]
@carldek please update with the import option.

**Comment by carldek** [comment]
Import Update complete
