### ISSUE TITLE
Leave Balance Screen

### ISSUE THREAD

**Issue by MartinKruger** [Mandiklopper/People-Connect#124]
[Senseable Ticket #278](https://senseable.co.za/scp/tickets.php?id=150)
**Nicholas Smit posted 15 Nov 17 @ 11:33** 
Hi Martin.

Could you possibly check what exactly updates the balances on the following screens, we seem to be getting different results for different screens. So if you could just let us know what exactly updates the balances and totals then I can look at getting those totals or calculations standardized so that all the screens five the same results.

Employee Leave Detail screen (CONSDLS)
Leave by Employee (GESCNE)
Leave Balance Enquiry (CONSCNG)

**Comment by kevmza** [comment]
Looks like all of them are dependent on their payslip

Leave by employee is linked to table CNGEMP

CNGEMP table is updated from the payslip calculation so that it shows the current balance of the employee.

The others look at the payslip at a point in time i.e. the payslip information for leave.

**Comment by kevmza** [comment]
Hi Nicholas, 

Please let me know if there is anything else we can assist with re this one.

Kiran confirmed that you spoke with him regarding this ticket.

Regards,
