### ISSUE TITLE
Approved Leave - Tracking Status Error

### ISSUE THREAD

**Issue by MartinKruger** [Mandiklopper/People-Connect#125]
[Senseable Ticket #281](https://senseable.co.za/scp/tickets.php?id=153)
**Emmanuel Edhedhe posted 16 Nov 17 @ 16:10**
Already approved leave which shows taken and balance correctly but display tracking status as Rejected on ESS and on Entry of absence screen.

**Comment by MartinKruger** [comment]
**Martin Kruger posted 29 Nov 17 @ 16:42**
This could have been due to re-integration of data tables during the testing time.

If you encounter this again, could you include screen shots/video or show us.

**Comment by MartinKruger** [comment]
**Emmanuel Edhedhe posted 07 Dec 17 @ 10:12** 
This issue is still been experience

**Comment by MartinKruger** [comment]
**Martin Kruger posted 07 Dec 17 @ 10:29 Ticket** _Assigned to Kevin Meyer_
When a new leave transaction is captured, the start status is currently 'Accepted', this has to be 'Requested'.
After the transaction is now approved, the status now shows 'Rejected' even though it was accepted.

I am thinking that the Local Menu probably changed or the code reference has.

Please check with Kiran if this has changed and how to correct it.

**Comment by MartinKruger** [comment]
**Kiran Ramnath posted 07 Dec 17 @ 12:34** 
Hi,

There are 2 issues 

1. The leave periods cycle start date's where incorrect (i.e. we needed to change it the financial year cycle and not the anniversary date cycle like we initially configured) 

I have fixed these periods on UBAUAT for 2017 on all leave types. Please fix the other years (formula below) and check the setup on each leave period (I saw 2017 period start and end dates was in 2015, I fixed). Do this for all years, all nature of event, and don't forget to transfer to PREPROD

max([F:CTR]DATANC,gdat$(1,1,((GMOIPAY = [0/0/0])*[F:CNG]YEA)+((GMOIPAY [0/0/0])*year(GMOIPAY))))

2. The leave initialization was run a very long time ago, and the balances are out dated. Remember that the employee balance gets updated with every latest payslip run. Because of this cycle change you will need to delete all the leave by employee records again and run leave initialization again, this will correct the leave cycle (I tested on employee A00750 if you want to have a look). Please do the corrections on the leave periods in point one first.

Regards,
Kiran

**Comment by janwvjaarsveld** [comment]
Stale ticket. Please re-open if this is still an issue
