### ISSUE TITLE
BRD Item: Viewing existing Exit requests

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/People-Connect#126]
HR Admin BRD (Exit Management) - 4.2.4.12 not implemented yet:

"On the employee contract, a link will be added to show the latest employee Exit logged on the ESS application.  The naming of the link will be Exit requests.  Once the user clicks on the link it will show a read only page with the data captured on ESS by the employee, HRBP and MSS by the Supervisor.  
"

**Comment by kevmza** [comment]
Hi there, I've added it as requested. Can be reviewed on 10.16.109.50.

Patch created to be patched to UAT and TEST.

**Comment by Mandiklopper** [comment]
@kevmza I had a look on 10.16.  Looks perfect but it seems like some info not showing listed in the request.  The comments of the HRBP and Supervisor also needs to show.  @MartinKruger please advise after our discussion.

**Comment by kevmza** [comment]
Hi Mandi,

Supervisor comment should be showing:

![image](https://user-images.githubusercontent.com/34372329/33982344-d4cc4582-e0b8-11e7-936e-9f99a94d1827.png)

Will follow up re the HRBP comment and discuss with Martin to confirm.

Regards,

**Comment by Mandiklopper** [comment]
@kevmza this is what I see as attached.
![exitreqview](https://user-images.githubusercontent.com/33479066/33983129-a7b8fe0c-e0bb-11e7-9dc0-fa66ef98cf1c.PNG)

**Comment by kevmza** [comment]
Hi Mandi,

Yes, it means there is no exit request data for that contract.

Look at another employee, 201705555 and 201705008 has content on NGADEV2

It hides the fields when empty.

I can disable the hiding?

Regards,

**Comment by Mandiklopper** [comment]
Ok perfect thanks.  The comments on the interview is the comments for the HRBP, so it seems like the supervisor comments then needs to be added.

No its fine, don't think you have to hide it

**Comment by kevmza** [comment]
Hi Mandi,

I’ve removed the hiding.

Supervisor Comments should also be showing in the “Exit Request – Supervisor” block just below “Exit Request - Interview” Block.

Please have a look on NGADEV2 and If you are happy I will patch out.

Kind regards,

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Supervisor comment and all information showing | Passed | All the information does show if the information is filled in or there is data to be shown, if there is no data it does not show. Checked through multiple employees, for some employees there is not enough data but with 'Kate Testington' all data is available and shown correctly.

**Comment by Mandiklopper** [comment]
@Yinka123 please test

**Comment by Yinka123** [comment]
Yet to be patched to the test environment, could not test for now.

**Comment by Yinka123** [comment]
Pass on NGDEV2

**Comment by kevmza** [comment]
Patch Created and ready to be patched to TEST.

PATCHFUNC_NGADEV\20180130_1202_SRC_126_KEMEY

**Comment by Mandiklopper** [comment]
@Yinka123 please test.
