### ISSUE TITLE
Unauthorized Absence

### ISSUE THREAD

**Issue by MartinKruger** [Mandiklopper/People-Connect#128]
**Emmanuel Edhedhe posted 17 Nov 17 @ 14:40** 
The workflow sent our was to HRBP and final Leave Admin.
But there is none for Exit Management.

I need more explanation as to when and how the exit management will get notification if it flows their way.

**Comment by MartinKruger** [comment]
**Jan Willem van Jaarsveld posted 28 Nov 17 @ 16:40** 
Has the Exit management been set up as a FYI on the Signature management tab??
It will go out on the final approval

**Comment by MartinKruger** [comment]
**Emmanuel Edhedhe posted 28 Nov 17 @ 17:56** 
Yes the Exit management is ticked on the Leave Admin position

**Comment by MartinKruger** [comment]
**Jan Willem van Jaarsveld posted 28 Nov 17 @ 18:02** 
Please recheck the Workflow process at the top, as Exit management is not part of the flow, but Work Ethics is.

This screen dump you provide is not the Signature management tab on Nature of Events that I am referring to.

**Comment by MartinKruger** [comment]
**Emmanuel Edhedhe posted 28 Nov 17 @ 18:13** 
The information was wrong its not Exit management but work ethics. 
What i meant was the Work Ethics team FYI in cases where they need to treat before it gets to the Leave Admin.

However it is ticked on the signature management

**Comment by MartinKruger** [comment]
**Jan Willem van Jaarsveld posted 29 Nov 17 @ 17:15** 
Can you please find out if this would be an issue if the Notification for Work ethics go out only upon approval by Leave admin. Alternatively we can CC them in the mail that goes to the Leave admin?

Please advise.

**Comment by MartinKruger** [comment]
**Emmanuel Edhedhe posted 05 Dec 17 @ 16:18** 
They should be CC in the mail that goes out to leave Admin, SO that in case they need to act on it they can do so and finalized it before the leave admin approves.

In a case where they dont need to take any action they have FYI and the leave admin does approves

**Comment by jwvjaar** [comment]
If Work Ethics is set up as FYI, they will receive a notification upon final approval.
