### ISSUE TITLE
Leave Plan

### ISSUE THREAD

**Issue by MartinKruger** [Mandiklopper/People-Connect#131]
**Emmanuel Edhedhe posted 20 Nov 17 @ 16:19** 

Relief clash requirement/validation/code should be part of Leave plan request process.

**Comment by MartinKruger** [comment]
**Martin Kruger posted 06 Dec 17 @ 17:30** 
Kiran did this on X3 and is busy with it on SS.
Note: This should have been a change request as this now contradicts the BRD. Point 12.9 on the BRD states you get your Relief approved before the plan is initiated and the Relief is not included in the leave plan approval. Point 12.13 is contradiction to this, though for Maternity leave only.

**Comment by kiranramnath** [comment]
Please test on UAT, deployed on Saterday

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Relief clash | Passed | Works as expected

**Comment by kiranramnath** [comment]
Patch -
310120181129_YSCSA_184_172_210_190_192_131_118_199_184_185_186_193_202
