### ISSUE TITLE
Disciplinary Attachments

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/People-Connect#153]
Attachment should be enabled and thereafter it must be viewable by Work Ethics team on both the Disciplinary Case and Disciplinary screens.

**Comment by MartinKruger** [comment]
once new case was created with attachment and then approved in disciplinary case, attachment was not carried over to disciplinary screen. 
( testing case 81)

**Comment by MartinKruger** [comment]
We tested with the wrong paperclip icon (used the standard one  and not the custom one).

The custom one did work as expected.

We can't open the attachments when the screen is GRIZO'd.  Please do not GRIZO the paperclip with the other fields. It is ok if they can add attachments after acceptance.

**Comment by stevencsgh** [comment]
Martin,


That is great, I will make that change to the paperclip is available after approval.


Steven.

________________________________

**Comment by stevencsgh** [comment]
Martin,


The paperclip is now accessible on the screen after "approval" .


Steven.


________________________________

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment
---- | ------------ | -----------
Paperclips work the same | Fail | On Disciplinary case both paperclips work the same, on Disciplinary the paperclip on right bar opens different attachment tab.
Peperclip accessible after "approval" | Passed | Works as expected.

**Comment by stevencsgh** [comment]
Removed custom paper clip from Case screen - user must use standard paper clip.

Changed description of paper clip on disciplinary screen so user can attach/view case attachments.
Standard paper clip can still be used for attaching items relating only to this disciplinary.

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment
-- | -- | --
Paperclip accessible after "approval" | Passed | Works as expected.
Paperclips work the same | Passed | Paperclip on "Disciplinary case" right bar and paperclip on "Disciplinary" screen is the same and related to case attachments. while right bar Paperclip on "Disciplinary" is for specific Disciplinary and not for case related attachments.

**Comment by Mandiklopper** [comment]
@Yinka123 please test.

**Comment by Yinka123** [comment]
Passed. Attachments with the paper clip was possible from both disciplinary and disciplinary case screens
