### ISSUE TITLE
WF: Suspension under investigation

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/People-Connect#154]
The email notifications for suspension under investigation that we got yesterday was wrong (it is attached).  The right one is the Indefinite Suspension notice in the template you were given.  The closing sentence is wrong in the attached.

**Comment by P1errevanZyl** [comment]
Changed last sentence to match Indefinite Suspension

**Comment by Mandiklopper** [comment]
@Yinka123 please test

**Comment by janwvjaarsveld** [comment]
has this been tested?

**Comment by Pappabeer** [comment]
Hi All has this item been closed?

**Comment by janwvjaarsveld** [comment]
Stale ticket. Please re-open if this is still an issue
