### ISSUE TITLE
Hide PORTAL TAB On Nature of Events 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#156]
Please remove the Portal tab on the nature of event as its currently not used on the current ESS screen

**Comment by jwvjaar** [comment]
Since the Nature of Events screen will not be used very often, I cannot see the purpose of hiding this tab. 
Parked.

**Comment by kevmza** [comment]
Patch created, will patch to UAT for test.

**Comment by kevmza** [comment]
Emmanuel

I have hidden the TAB for you on UAT.

Please test and confirm if this ticket may be resolved.

Thanks.

**Comment by EmmanuelEdhedhe** [comment]
Thanks Yes I confirm the TAB have been removed and the ticket resolved.
