### ISSUE TITLE
FIELD ERROR - EMPLOYEE ID

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#158]
Attempts by HRBP team member ( A15774) to process Relief Assignment for the following A07355, A07355 & A09932 results in the Field Error - Employee ID error message '001: You cannot access this service' upon entry of employee ID on the single processing screen.

Please urgently look into this issue

**Comment by Mandiklopper** [comment]
@jwvjaar please look into this.

**Comment by Mandiklopper** [comment]
@chidiif please look into this and check if this is perhaps an access issue

**Comment by chidiif** [comment]
No access codes were applied to these Employees so it is pretty difficult to say what the problem is. JW was taking a look at it, do you know if he found anything?

**Comment by Mandiklopper** [comment]
@carldek please look into this.  Please correct +- 70 cases where employees services (category) shows 001 instead of 1 as example.  This is causing issues with relief assignments

**Comment by carldek** [comment]
Imported 80 Employees correct "Job Category" code
