### ISSUE TITLE
WF - Approved Leave FYI to GHHR and GMD

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#164]
Upon final approval for All leave type application for grades AGM and above, email notification FYI must be sent to GHHR and GMD

**Comment by MartinKruger** [comment]
This ticket is a duplication of #142 .

**Comment by EmmanuelEdhedhe** [comment]
My Bad

**Comment by MartinKruger** [comment]
No prob. Just trying to keep it simple.
