### ISSUE TITLE
Leave application restriction Rule Maternity & Annual 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#171]
Where an employee has applied for and taken maternity leave earlier in the calendar year, the portal should not grant such an employee access to apply for annual leave

**Comment by MartinKruger** [comment]
Please complete the change request document to get this process started.

**Comment by kiranramnath** [comment]
@EmmanuelEdhedhe This should be managed with balance control configuration, as previously discussed. Once maternity leave is taken, we should/are setting the annual balance to 0. So if you enable balance control on the annual leave nature of event, the employee will not be allowed to take any further annual leave. @NicSmit and @Haylz0617 please jump  in if I am wrong.

**Comment by MartinKruger** [comment]
@EmmanuelEdhedhe , this is leave config and does not require Functional Dev assistance.
i.e. if the YTD for Maternity Lve is >0, don't allow Annual Lve.
