### ISSUE TITLE
Leave Plan Annual & Maternity 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#172]
•Leave Plan 
Annual & Maternity Leave plan. On both leave application system should reference the leave plans already submitted for selection and automatically update the start and End dates on the application 

The fields Estimated Delivery and Attachment are not required for Annual Leave   Plan.  Please remove

**Comment by kiranramnath** [comment]
SRC_YSCSA_LEAVE_190_184_185_186_193_172_210_202_192_240120181239

X3 and ESS

**Comment by LindaleeConradie** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Reference to leave plan | Pass | In ESS, it automatically updates the start and end dates as expected.

**NOTE**

In X3, there is no list for planned leave. Although when the dates entered regarding eg. annual leave the rest of the information is referenced from the leave plan and is automatically filled in.

**Comment by kiranramnath** [comment]
Patch -
310120181129_YSCSA_184_172_210_190_192_131_118_199_184_185_186_193_202
