### ISSUE TITLE
INCOMPLETE UPDATE OF ESS PROFILE FOR APPROVED ESS REQUEST

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#178]
ESS request for staff A14106 to add his son born on 20/10/2017 has been approved by the supervisor and HRBP but it did not update the system correctly;

•	HMO Dependent: Yes
•	Hospital 1 selected: Fereprod Medical Center

The HMO dependent flag was not ticked on the system and the hospital field is blank.

Note however that the email notification from WF monitor shows Hospital 1 (Employee): Fereprod Medical Center, even though it was the hospital under the dependant that was entered. This hospital is not showing for this new dependant or for the employee. The employee has a different hospital Avon Medical Services Ltd (Clinic)

**Comment by jwvjaar** [comment]
The table still indicated that the transaction's status was requested. After approval it got processed.

It is possible that something could have gone wrong with the initial approval. Will monitor if this problem occurs again.
