### ISSUE TITLE
Positions available for Staff movement  - Single vs. Bulk Processing

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#179]
For the same staff movement, the positions in the drop down when using single processing is not the same as when using bulk processing. 

For a sample Relief Assignment Staff movement for A08414 with details for State / Directorate / Division / Dept / Branch as follows-  TA1/DR013/DV039/BR363, the positions are as shown below for each method;

Single Processing (4 positions available)
1. J0012019000432
2. J0188019000161
3. J0680019000430
4. J0680019000431

Bulk Processing (9  positions available)
1. J0012019000431**
2. J0012019000432
3. J0013019000551**
4. J0077019000444**
5. J0188019000161
6. J0379019001831**
7. J0379019001832**
8. J0680019000430
9. J0680019000431

Based on the above, a HRBPs complained of noT having a Branch Manager position in BR363 and upon creation of  J0012019000432 positions by Bola, it was visible under single processing view, and so there are now 2 BM positions for BR363 - J0012019000432 & J0012019000431 as seen under the bulk processing view.

Please investigate this and fix.

**Comment by jwvjaar** [comment]
Filter has been fixed
