### ISSUE TITLE
Access to Exit Interview Tab for Exit Request Processing

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#182]
Current:

Only HRBP Team Leads have access to modify exit requests on the Exit Interview tab and to 'Process' or 'Withdraw' the exit request. HRBP Team members only have viewing rights

Proposed:

HRBP Team Members should have the same rights as the HRBP Team Leads i.e. modify rights on the Exit Intervie tab only to enable update to Date, Interview Status and Comments and to 'Process' or 'Withdraw' the exit request

**Comment by chidiif** [comment]
HRBP Team Member profile have been updated to allow modification of Date, Interview Status and Comments fields. @roberteta Kindly advise users to test and revert.

**Comment by roberteta** [comment]
HRBP Team Members now have the same rights as the HRBP Team Leads i.e. modify rights on the Exit Interview tab

**Comment by chidiif** [comment]
@MartinKruger, Kindly assist to look at this case. My assessment is that it will require some development.
