### ISSUE TITLE
Annual Leave Plan 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#184]
**Annual Leave**
I.	Annual Leave plan should not be more than the staff entitlement number of days as per grade
II.	At the point of planning the employee must enter plan to the sum total of his entitlement
Consider Maternity leave also Max 60 days
III.	Delete or modify the plan if there are changes to already approved plan and add a line, to sum up  the total number of days of entitlement  
IV.	On annual Leave plan, relief clash must look at the relief leave plan start and end date already entered to ascertain the relief is available at the point of making the leave plan.  
V.	On Annual Leave application – The system must have a field that references the approved planned leave for selection and automatically captures the start and end date. 
Change request

For leave the request, the system should auto-populate the field "End date" when the user keys in start date, type of leave and number of days.

The application should sum up the number of days the employee is entitled too when planning annual leave. System should not allow the user save leave plan   if total number of days exceeds the total number of leave day (or  leave remaining balance)

Leave Plan MUST be available and Approved before   users can apply for either Annual or Maternity leave

**Comment by kiranramnath** [comment]
@EmmanuelEdhedhe  please can you elaborate on III.

III.	Delete or modify the plan if there are changes to already approved plan and add a line, to sum up the total number of days of entitlement

**Comment by EmmanuelEdhedhe** [comment]
What that means is If the employee makes any adjustment/changes to his already planned leave. he must make sure that the sum total still adds up to the entitlement number of days.

**Comment by kiranramnath** [comment]
SRC_YSCSA_LEAVE_190_184_185_186_193_172_210_202_192_240120181239

ESS and X3

**Comment by ZanderCronje** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
I  &  II | fail | When creating a leave plan, the max number of days (60 days)  is not valid, due to the fact that a leave plan can be created with eg. 86 days
IV | Passed | An additional leave plan cannot be created if the dates clash with an existing leave plan
V | Passed |  When creating a leave request, when an anual leave plan is selected the dates fields are automatically filled in.

**(NGADEV)**

**Comment by LindaleeConradie** [comment]
![image](https://user-images.githubusercontent.com/34658211/35510152-a8f03c64-04ff-11e8-9182-1b9ed252829f.png)

**Comment by ZanderCronje** [comment]
After going under nature of events and changing the maximum number of days allowed to 60, an error message was given showing that the max days were exceeded when creating a leave request

Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
II  |  Pass  |  Changed the max days under nature of events

(NGADEV)

**Comment by EmmanuelEdhedhe** [comment]
Hi Zander. Just a quick one. Did the No 1(I) requirement on the Annual leave days Pass?

**Comment by kiranramnath** [comment]
Patch -
310120181129_YSCSA_184_172_210_190_192_131_118_199_184_185_186_193_202

**Comment by ZanderCronje** [comment]
Yes, no (1) passed

**Comment by EmmanuelEdhedhe** [comment]
I.	Annual Leave plan should not be more than the staff entitlement number of days as per grade = Fail 

![image](https://user-images.githubusercontent.com/34434368/35909126-42716398-0bfb-11e8-883b-9bea8bb5e384.png)
