### ISSUE TITLE
Annual Leave application Spill to Next Year

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#186]
Employee can apply for leave across years 2017 – 2018 but must only be one week into the new year e.g. Only the first week in 2018  28/12/2017 to 05/01/2018

*             Staff Annual leave cannot extend beyond the first week of the next financial year
Only applicable to Annual Leave  

Users   should be able to apply for leave into the next financial   year i.e. 1st week in January

**Comment by kiranramnath** [comment]
SRC_YSCSA_LEAVE_190_184_185_186_193_172_210_202_192_240120181239
X3 and ESS

**Comment by LindaleeConradie** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------

Spill into first week of following year | Pass | allowed to spill into first week of following year as expected.

**Comment by kiranramnath** [comment]
Patch -
310120181129_YSCSA_184_172_210_190_192_131_118_199_184_185_186_193_202

**Comment by EmmanuelEdhedhe** [comment]
@janwvjaarsveld Has this been patched onto PREPOD  & PROD?

**Comment by janwvjaarsveld** [comment]
@EmmanuelEdhedhe yes, this has been moved to both

**Comment by EmmanuelEdhedhe** [comment]
Completed
