### ISSUE TITLE
Leave Type View

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#187]
• Employees should only be able to view and apply for the leave type that is applicable to them via ESS. (Req 004 BRD)

Although the employee may be able to see the relevant leave types, an error is thrown when they select as invalid/ Nature of event not compatible. 
The client doesn't want them to see the leave types on their drop-down list 

Paternity   leave should not be seen as an option for a female employee on the leave   request screen

Maternity   leave should not be seen as an option for a male employee on the leave   request screen

**Comment by kiranramnath** [comment]
The current ESS  framework does not allow us to filter the same way leave types are filtered on X3, hence R&D has stop the selction of invalid leave types by throwing an error

**Comment by kiranramnath** [comment]
I have addressed on NGADEV2 and will patch in with other leave items in progress

**Comment by kiranramnath** [comment]
@EmmanuelEdhedhe can I close this item?

**Comment by EmmanuelEdhedhe** [comment]
Yes, you can. Once the patch is done on UBA and tested 

Thanks

**Comment by kiranramnath** [comment]
@EmmanuelEdhedhe please refer to my previous comment. We cannot develop filter at the moment as explained, prior, may I please close this ticket.

**Comment by EmmanuelEdhedhe** [comment]
@kiranramnath You can close it or put on backlog, But I need the feedback on the Defect sheet sent by UBA to forward to them for consideration

**Comment by kiranramnath** [comment]
@EmmanuelEdhedhe I believe all feedback on the sheet are logged as tickets, if not please log them and I will address follow up on the ticket.

**Comment by EmmanuelEdhedhe** [comment]
This has to be moved to Backlog as the framework cant filter as per client requirement but will pop us the error message of incompatible.
