### ISSUE TITLE
WF- Staff Copy on all Approval 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#188]
Employee should be CC’ed on all workflow notification that goes out to each stakeholder for approval so he can know the stage/level/position of his/her request 

Example Once the Supervisor receives the notification, the Employee will be copied in the supervisor email and same when it gets to the 2nd supervisor up to  the final approval 

Notification   emails should be sent to the initiator at every stage of the request process

**Comment by jwvjaar** [comment]
Change request must be completed

**Comment by EmmanuelEdhedhe** [comment]
Sent to the client

**Comment by EmmanuelEdhedhe** [comment]
The change request has been signed off.

Please implement and patched onto PROD

**Comment by EmmanuelEdhedhe** [comment]
@janwvjaarsveld Confirm if this has been patched onto PROD

**Comment by janwvjaarsveld** [comment]
confirmed

**Comment by MartinKruger** [comment]
@EmmanuelEdhedhe, please DO NOT instruct anyone to implement anything to PROD unless you have tested the issue thoroughly!

In this instance you only asked **how to test** the ticket after you have given the instruction to implement on PROD.

**Comment by EmmanuelEdhedhe** [comment]
Note Martin, Point to note i asked "**how it works**" reason was that I got only one email and addressed all stakeholders. I wanted to find out if this is correct or the employee was to receive a separate email stating that the supervisor was to sign

![image](https://user-images.githubusercontent.com/34434368/38733965-3169c9e4-3f24-11e8-85cd-306152b87cca.png)
