### ISSUE TITLE
Backdate Sick Leave

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#189]
Backdated sick leave request should be allowed and made available on the system.

This should be applicable to only sick leave

**Comment by kiranramnath** [comment]
Done on   10.16, added tick box ("Allow backdate entry")to the nature of   event setup screen to  mark nature of   events where back dated leave is    allowed and added validation on ESS and absence entry (X3)

**Comment by kiranramnath** [comment]
Patch - SRC_YSCSA_LEAVE_190_184_185_186_193_172_210_202_192_240120181239

**Comment by kiranramnath** [comment]
X3 and ESS to be tested

**Comment by LindaleeConradie** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Allow backdated sick leave request | Pass | After ticking the tick box which was added and requested for backdated sick leave, it was allowed and requested. Then trying the same for backdated annual leave request it was not allowed. Therefor it worked as expected.

**Comment by EmmanuelEdhedhe** [comment]
Completed.
