### ISSUE TITLE
Data Migration Checklists

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/People-Connect#19]
Please complete the Data Migration Checklist for all Data migration completed:

*  Employee Data
*  Position Data 
*  Standard Job Data
*  Site data 

@carldek please check with me as I do have some of these already completed.  We just need to finish it up.

**Comment by Mandiklopper** [comment]
This has been completed by @carldek.  Under review by Mandi.

**Comment by Mandiklopper** [comment]
Emailed to Robert by Mandi.

**Comment by janwvjaarsveld** [comment]
Stale ticket. Please re-open if this is still an issue
