### ISSUE TITLE
Sick Leave 1 & 2 - Remove relief Field

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#190]
Sick Leave SL1 & SL2 – Remove the relief field for both sick leaves

If Relief is unticked on nature of event – Hide on ESS, greyed out on entry of absence 

MSS->Field   validation
On MSS   screen, Reason field should not be available for manager to populate as HRBP   handles this during approval for both    Sick and extended sick leave

On MSS   screen, Relief field should not be mandatory for manager to populate

Reason - No pay,   Full & half pay, Should only be available to HRBP and Leave Admin and not  to Manager

**Comment by kiranramnath** [comment]
Emmanuel   to deactivate the relevant reasons on Sick extended

**Comment by EmmanuelEdhedhe** [comment]
Reasons deactivated.

However, the system still says the reason filed is mandatory and I cant proceed with the transaction.

Kindly remove the reason field

**Comment by kiranramnath** [comment]
I have update on NGADEV2 and will patch over with  other  leave defects.

**Comment by kiranramnath** [comment]
Patch name - SRC_YSCSA_LEAVE_190_184_185_186_193_172_210_202_192_240120181239

**Comment by kiranramnath** [comment]
X3 and ESS

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Relief field mandatory for SL1 and SL2 | Passed | Works as expected, Relief is not mandatory for sick leave request.
Reason field MSS | Passed | Works as expected. When creating leave for subordinate, the reason field disappears for SL1 and SL2. Also not mandatory.

**Comment by kiranramnath** [comment]
Patch -
310120181129_YSCSA_184_172_210_190_192_131_118_199_184_185_186_193_202

**Comment by EmmanuelEdhedhe** [comment]
@janwvjaarsveld  has this been patched onto PREPOD  & PROD

**Comment by EmmanuelEdhedhe** [comment]
Tested
