### ISSUE TITLE
Course of Study Attachment 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#191]
**Course of Study**
II.	The attached document should be part of the email notification sent to the approval (same logic or format as dependant attachment) in other for the approver to view and make a decision

**Comment by LindaleeConradie** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Attachment was sent with email to be reviewed | Pass | Put in request for study course. Email was received by supervisor with the document attached as expected.

**Comment by EmmanuelEdhedhe** [comment]
Please patched onto PROD

**Comment by EmmanuelEdhedhe** [comment]
Tested on PREPOD attachment sent with email - PASS.

Please patch onto PROD and close ticket.

**Comment by EmmanuelEdhedhe** [comment]
Please confirm patch on PROD

**Comment by EmmanuelEdhedhe** [comment]
Resolved 

![image](https://user-images.githubusercontent.com/34434368/38975925-e4ec2504-43af-11e8-97a1-0445120e99a7.png)
