### ISSUE TITLE
Number of Directorate heads on leave 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#192]
**Change request**
Only three Directorate Heads can be on leave at the same time

**Comment by kiranramnath** [comment]
SRC_YSCSA_LEAVE_190_184_185_186_193_172_210_202_192_240120181239

ESS and X3

**Comment by EmmanuelEdhedhe** [comment]
Additional Information 

The maximum number of Executive Committee (EXCO) members that can be on annual leave at the same time is three(3)
This is only applicable to annual leave 
Specific EXCO members forms part of this population/group

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
No more than 3 directorate heads can be on leave at the same time | Passed | Works as expected, as soon as the fourth directorate head applies for leave a message pops up and indicates that no more than 3 EXCO members are allowed to go on leave at the same time.

**Comment by kiranramnath** [comment]
Patch -
310120181129_YSCSA_184_172_210_190_192_131_118_199_184_185_186_193_202

**Comment by EmmanuelEdhedhe** [comment]
Completed
