### ISSUE TITLE
Leave Request Rule

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#193]
You cannot request for any leave type more than 1 month before the commencement/start date

**Comment by kiranramnath** [comment]
Does this include extended sick leave? People going for operations in like 3 months can only apply for leave a month before procedure?

**Comment by EmmanuelEdhedhe** [comment]
This I believe is only applicable to Annual Leave type. 

Let wait for the CR document with details from UBA.

**Comment by kiranramnath** [comment]
SRC_YSCSA_LEAVE_190_184_185_186_193_172_210_202_192_240120181239

ESS and X3

**Comment by LindaleeConradie** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Date for leave more than month | Pass | Worked as expected.

**Comment by kiranramnath** [comment]
Patch -
310120181129_YSCSA_184_172_210_190_192_131_118_199_184_185_186_193_202

**Comment by janwvjaarsveld** [comment]
on PREPROD and PROD. Please confirm

**Comment by EmmanuelEdhedhe** [comment]
Works on PREPOD & PROD

Tested - PASS
