### ISSUE TITLE
X3 Application Error on Single Processing of Staff Movement

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#196]
HRBP Team Lead A00526 gets the error message below on attempt to approve a Redeployment staff movement for A21208

 X3 Application Error
Table: YMOVECTR [YMOV]
Key: A21208 A21208NG001 01/01/2018 12001 12001
Obsolete Record
Transaction Stopped

Please investigate and resolve

**Comment by jwvjaar** [comment]
There is one transaction that has been cancelled and another that is awaiting GHHR approval. And A00526 is displayed as a previous approver.
