### ISSUE TITLE
BULK PROCESSING OF STAFF MOVEMENT

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#197]
The issues are as follows;

•	Bulk staff movements initiated by HRBP team members are not available for bulk approval via MSS > Staff movement approval screen similar to that for GHHR and GMD. This was meant to be available based on feedback from you to Martha & I during one of your previous trips to Lagos.
•	No notification was sent out to HRBP team lead A00526  on staff movement loaded as bulk
•	The 25 staff movement loaded as bulk by A11598 (sample in table below) is not seen in the single processing screen unlike those loaded by Osayi (A07718 ) and Ikenna (A23886) that is seen on the single processing screen

A09915
A12841
A23245
A20120
A13500
A20937

**Comment by jwvjaar** [comment]
The MSS functionality has been added to PREPROD.

Awaiting feedback from Martha for WF notification wording

**Comment by jwvjaar** [comment]
WF will not be added at this point, as per email.
Sent: Wednesday, January 10, 2018 8:49 AM
Subject: RE: BULK PROCESSING
