### ISSUE TITLE
ERROR ON EMPLOYEE ARRIVAL SCREEN

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#198]
Attempt to create a new employee on the employee arrival screen is coming up with the X3 Application Error : Error on counter ENT.

Please urgently look into this as this new employee needs to be created on the system prior to his resumption date

**Comment by roberteta** [comment]
Upon conversion, contract staff with CE employee ID are promoted and their employee ID changed manually from CEXXXX to AXXXX.. Feedback from Mandi and the previous experience was that the  manually assigned numbers are taken into consideration by the system in auto generating and assigning ID to new employes creted via the Staff Arrival screen. See the examples below. The HRIS administrator did not update the next sequence number after manually changing employee IDs from CEXXXX to AXXXX

Numbers assigned by System – New hires : A24251 to A24257
Numbers assigned manually – Converted contract staff: A24258 to A24268
Skipped Employee ID – A24269
Numbers assigned manually – Converted contract staff: A24270 to A24273
Numbers assigned by System – New hires : A24274 to A24276
Numbers assigned manually – Converted contract staff: A24277 to A24281 – Done a few minutes ago

Upon attempt to create a new employee, the error message below was displayed

X3 Application Error. 

Error message ‘ A24281 Table: EMPLOID (ID key A24281, Record already exist, transaction stop’

**Comment by roberteta** [comment]
What is required is for the system to take into consideration the last used employee ID (whether assigned automatically by system or manually assigned) in assigning the next employee ID so the next sequence number does not have to be updated manually. In the interim, the HRIS Administrator (Bola) may need access and taken through how to maintain the next sequence number after each manual assignment of employee ID.

**Comment by roberteta** [comment]
Please set the next sequence number as A24282 to enable the creation of new employees via the employeearrival screen

**Comment by jwvjaar** [comment]
The next sequence number has been set. We are able to set the next sequence number by looking at the last employee number used, however there are currently sequence numbers > A30000, this will leave a gap of +-5700 sequence numbers.
