### ISSUE TITLE
Date range

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#199]
The system should not allow the user to backdate the start and end date for all leave requests apart from sick leave.

**Comment by kiranramnath** [comment]
Done on   10.16, added tick box ("Allow backdate entry")to the nature of   event setup screen to  mark nature of   events where back dated leave is    allowed and added validation on ESS and absence entry (X3)

**Comment by kiranramnath** [comment]
Patch - SRC_YSCSA_LEAVE_190_184_185_186_193_172_210_202_192_240120181239

**Comment by kiranramnath** [comment]
X3 and ESS

**Comment by LindaleeConradie** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Backdate of leave | Pass | Error message is shown when a back date is selected for any leave besides sick leave as expected.

**Comment by kiranramnath** [comment]
Patch -
310120181129_YSCSA_184_172_210_190_192_131_118_199_184_185_186_193_202

**Comment by EmmanuelEdhedhe** [comment]
Completed
