### ISSUE TITLE
Stakeholders - Staff movement

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/People-Connect#2]
**Email from Robert Eta:**

See redeployment notification received none of stakeholder i.e. receiving and releasing supervisors, payroll, etc.

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=113 - Assigned to Jan Willem

**Comment by Mandiklopper** [comment]
Staff, HRBP member, HRBP team lead, receiving and releasing supervisors and payroll will now be copied in the same email. However, the stakeholder group for Payroll must be loaded.  I have requested a list of the Payroll Stakeholders from Bukky / Robert.

**Comment by Mandiklopper** [comment]
@roberteta has provided the Payroll stakeholders email address.  JW to confirm if what is needed to complete this task.

**Comment by Mandiklopper** [comment]
JW confirmed that this information is enough.  Mandi to complete the stakeholder on Preprod with detail.  Once done it will work correctly.

**Comment by Mandiklopper** [comment]
Completed.  Please retest

**Comment by Mandiklopper** [comment]
Reopened on Senseable - http://senseable.co.za/scp/tickets.php?id=113 - Assigned to JW.

**Comment by Mandiklopper** [comment]
@roberteta please advise if the stakeholders did not physically receive an email or could you not view it on Workflow Monitor?

**Comment by roberteta** [comment]
@ Mandi, The stakeholders did not physically receive any email, neither was thi seen on WF Monitor

See sample email below showing recipients

From: PeopleConnect@ubagroup.com [mailto:PeopleConnect@ubagroup.com] 
Sent: Wednesday, November 22, 2017 1:26 PM
To: Okwubido, Chiagozie
Cc: Okafor, Amaka; Nze, Chima; Nnorom, Martha; Iragbonse, Yonke; Payrollvalidation
Subject: Redeployment A23928 - Chiagozie Okwubido

Dear Chiagozie Okwubido,

We are pleased to inform you of your Redeployment.Please find the details below:

DEPARTMENT/BRANCH: Regional Internal Control Lagos (DP255)
LOCATION: 11-13, Warehouse Road Apapa (0182)
NEW JOB TITLE: Regional Control Officer
NEW SUPERVISOR: Amaka Okafor
EFFECTIVE DATE: Friday, 01 DEC 2017

PREVIOUS SOL ID: 0450
PREVIOUS JOB TITLE: Regional Control Officer

You are expected to hand-over to the next line officer or your supervisor and report to your new supervisor on the Effective Date.
Please note that failure to resume at your new location on the effective date will amount to policy infraction. 
We wish you the best in your new assignment.

Thank you.

Human Capital Management

**Comment by Mandiklopper** [comment]
@roberteta this will not show on the workflow monitor.  This is still in progress as this is a custom development that the Dev team are working on.  
In the example mail Payroll validation were included the cc line.  Which other stakeholders are you referring to?

**Comment by roberteta** [comment]
Hello Mandi,

The following stakeholders are not getting the staff movement notifications;

•	2nd level supervisors (both releasing and accepting)
•	Branch Managers(BM) for branch staff



This is based on review of sample email notifications sent out. See sample below

From: PeopleConnect 
Sent: Monday, November 27, 2017 5:36 PM
To: Abdulganiyu, Bashir <bashir.abdulganiyu@ubagroup.com>
Cc: Oyewale, Abdulrasheed <abdulrasheed.oyewale@ubagroup.com>; Jamgbadi, Kayode <kayode.jamgbadi@ubagroup.com>; Abdul, Musa <Musa.Abdul@ubagroup.com>; Abbagana, Zainab <zainab.abbagana@ubagroup.com>; Payrollvalidation <Payrollvalidation@ubagroup.com>; User_Admin HO <user_admin.ho@ubagroup.com>; Mohammed, Mistura <mistura.mohammed@ubagroup.com>; Akinpelu, Comfort <comfort.akinpelu@ubagroup.com>; Adeyemi, Elisha <elisha.adeyemi@ubagroup.com>; Abdulkareem, Ahmed <ahmed.abdulkareem@ubagroup.com>; Sagay, Israel <israel.sagay@ubagroup.com>; Adeshina, Babajide <babajide.adeshina@ubagroup.com>; Are, Olasunkanmi <Olasunkanmi.Are@ubagroup.com>; ITCARE <ITCARE@ubagroup.com>; Oprisk Mgt Team <opriskmgtteam@ubagroup.com>; ConfirmationTeam <ConfirmationTeam@ubagroup.com>; Recordsteam <recordsteam@ubagroup.com>; Isioma-Nwaligbe, Soso <soso.isioma-nwaligbe@ubagroup.com>; UBAAcademy <ubaacademy@ubagroup.com>; Seidu, Christy <Christy.Seidu@ubagroup.com>; Chuks-Ngwu, Christie <christie.chuks-ngwu@ubagroup.com>
Subject: Relief Assignment A09630 - Abdulganiyu Bashir

Dear Abdulganiyu Bashir,

We are pleased to inform you of your Relief Assignment.Please find the details below:

DEPARTMENT/BRANCH: CMC/ZPC Gombe (BR381)
LOCATION: Biu Road  ,Gombe (0303)
NEW JOB TITLE: Head Cash Management Center
NEW SUPERVISOR: Abdulrasheed Oyewale
EFFECTIVE DATE: Wednesday, 22 NOV 2017
COMPLETION DATE: Sunday, 03 DEC 2017

PREVIOUS SOL ID: 0303
PREVIOUS JOB TITLE: Cash Officer

You are expected to hand-over to the next line officer or your supervisor and report to your new supervisor on the Effective Date.
Please note that failure to resume at your new location on the effective date will amount to policy infraction. 
We wish you the best in your new assignment.

Thank you.

Human Capital Management

**Comment by Mandiklopper** [comment]
Reopened on Senseable.

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Emails sent to 2nd level supervisors (both releasing and accepting) and Branch Managers(BM) for branch staff | Passed | Works as expected when all the supervisors are linked as needed.

**Comment by janwvjaarsveld** [comment]
Patch name: 20180205_1215_#2_JWVJA

**Comment by ArmandCtz** [comment]
![image](https://user-images.githubusercontent.com/35450069/35963361-277f3ebc-0cbd-11e8-8290-bc4b70694859.png)

**Comment by ArmandCtz** [comment]
Patched from NGADEV to NGATEST

**Comment by Mandiklopper** [comment]
@Yinka123 please complete the test.

**Comment by janwvjaarsveld** [comment]
Has this been tested?

**Comment by roberteta** [comment]
@Mandiklopper  and @Yinka123 please respond

**Comment by Yinka123** [comment]
It will be tested and before lunch tomorrow, status updated.
