### ISSUE TITLE
Email notifications for sanctions

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/People-Connect#20]
Email notifications for sanctions are not going to all stakeholders.  Please ensure that all stakeholders included in the attached
[Sanction_Disciplinary Notification List.docx](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1457387/Sanction_Disciplinary.Notification.List.docx)
 stakeholder list get notifications.

**Comment by Mandiklopper** [comment]
https://senseable.co.za/scp/tickets.php?a=open - Logged and not assigned yet.  Ticket 254

**Comment by Mandiklopper** [comment]
Emailed @Adebukola to request the correct stakeholders and Letter templates for all outcomes.  @Adebukola  please follow up with the work ethics team.

**Comment by Mandiklopper** [comment]
All workflows for sanction outcomes have been set to Active at 11:00 NGN time on 22 Nov 2017.
