### ISSUE TITLE
Nomenclature 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#201]
On the   "My leave plan" screen, the heading "Approved reliefs"   should be renamed to "Relief" i.e.    when user yet to select relief    this is misleading to the users

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Approved Relief set to Relief | Passed | Everything is changed as expected

**Comment by EmmanuelEdhedhe** [comment]
Completed
