### ISSUE TITLE
Validation message

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#202]
1. Change   "Insertion impossible in the YRELIEF collection of the C_YRELIEF   class" error message to "Maximum of 2 relief staff can be   selected"
--

2. The error message displayed on the screen when the user keys in invalid characters in the box fields on the "Employee courses" is unclear.   Please change validation message to reflect the actual error i.e invalid   characters
--

**Comment by kiranramnath** [comment]
SRC_YSCSA_LEAVE_190_184_185_186_193_172_210_202_192_240120181239

ESS only

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Change error message | Park | 
Error message on "Employee Courses" screen | Passed | When error message shows it is clear on what is needed and what was wrong. Works correctly.

**Comment by kiranramnath** [comment]
Patch -
310120181129_YSCSA_184_172_210_190_192_131_118_199_184_185_186_193_202

**Comment by EmmanuelEdhedhe** [comment]
Please, confirm Patch is on PROD so i can close this ticket

**Comment by EmmanuelEdhedhe** [comment]
![image](https://user-images.githubusercontent.com/34434368/38782628-b26a20d8-40f6-11e8-9398-e0521617b83a.png)
