### ISSUE TITLE
ESS - Leave transaction 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#205]
User should not be able to access the  "create"  action button in the Pending Leave   Transaction Section/Grid

**Comment by jwvjaar** [comment]
DEMCONGEESS - ACREATE link on Page set to Inactive.

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
 User access to "create" action in the Pending Leave Transaction grid | Passed | Works as expected

**Comment by EmmanuelEdhedhe** [comment]
Completed
