### ISSUE TITLE
Calendar Year Display

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#209]
The comma in the year should be removed

**Comment by kevmza** [comment]
Space has been removed. Will have to test first and need to discuss with Martin the changes made as locale had to be changed. Might need to create a copy of the locale as it will probably be overwritten when patching. 

Will revert soonest.

Thanks.

**Comment by EmmanuelEdhedhe** [comment]
Thanks Kevin. 

The workaround I did was to change the locale to UK English and the comma wasn't there but instead there was a space which is manageable but however, it means all user profile should be defaulted to UK English. Just an FYI.

**Comment by kevmza** [comment]
Thanks for the response.

I have changed the default one to a space separator for en-US this will however probably be overwritten when patching and changed back to comma.

I've in the interim also created a custom locale called UBA_en-US just need to talk to Martin to get the go ahead and we can change the default to that globally. 

Regards,

**Comment by kevmza** [comment]
Please test on 10.16

**Leave Plan**

Changes made:

Screens: YLVPLN0
Created TCH_YCALYR as Alphanumeric type. 

Classes: YLVPLNH and YLVPLN 
Created TCH_YCALYR Alphanumeric type.

Representations: YLVPLN
Created TCH_YCALYR with Property YLVPLNH.TCH_YCALYR visible on edit, detail and query facet. 

Set CALYR to invisible on edit, detail and query facet

Added in **YLVPLNH_CSPE** 

**lines 28-32**($PROPERTIES):

When "TCH_YCALYR"
    Case [L]ACTION
      When "CONTROL" : Gosub CONTROL_TCH_YCALYR
      When "PROPAGATE" : Gosub PROPAGATE_TCH_YCALYR
    Endcase

 **Line 68**($AREAD_AFTER)
 this.TCH_YCALYR = num$(this.CALYR)


**Line 216 - 220**($CONTROL_TCH_YCALYR) #kemey #ticket 209

If !pat(this.TCH_YCALYR, '####')
  ASTATUS=fmet GACTX.ASETERROR("Calendar Year","Length must be four, numeric values only.", [V]CST_AERROR)
Endif

Return

Added Line **224 - 228**

$PROPAGATE_TCH_YCALYR #kemey #ticket 209

this.CALYR = val(this.TCH_YCALYR)

Return

Added in **YLVPLN_RSPE** 

**Lines: 10**($METHODS) 
When "AQUERY_TRANS_AFTER" : Gosub AQUERY_TRANS_AFTER
**Lines: 30**($AQUERY_TRANS_AFTER)
this.YLVPLNH.TCH_YCALYR = num$(this.YLVPLNH.CALYR)

**Leave Balances**/**Annual leave by employee**

Screens: CNE1 added TCH_YEA as Alphanumeric type
Classes: CNGEMPESS added TCH_YEA as Alphanumeric type
Representations: CNGEMPESS added TCH_YEA with Property: CNE.TCH_YEA set to visible on detail and query facet

Set YEA on Representations(CNGEMPESS) to invisible

Added in **CNGEMPESS1_RSPE**
**Line 26**($AREAD_AFTER) : this.CNE.TCH_YEA = num$(this.CNE.YEA) #keymey
**Line 60**(AQUERY_TRANS_AFTER) : this.CNE.TCH_YEA = num$(this.CNE.YEA) # kemey

**Comment by kevmza** [comment]
Removed  field TCH_YCALYR from Class YLVPLN

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Comma in year | Passed | No more comma in the year
Negative test | Passed | Cannot enter less than 4 or more than 4 numeric characters, cannot enter normal characters, cannot enter four zero,s or an incorrect date.

**Comment by kevmza** [comment]
Patch applied to NGADEV.
Patch File Attached.


[209CalendarYearDisplay_180117.zip](https://github.com/Mandiklopper/People-Connect/files/1638826/209CalendarYearDisplay_180117.zip)

**Comment by kevmza** [comment]
Added TCH_YCALYR to YLVPLNMSS class
Added TCH_YCALYR to YLVPLNMSS representation

Made invisible CALYR on QUERY and DETAIL Facet

Added: 
this.YLVPLNH.TCH_YCALYR = num$(this.YLVPLNH.CALYR)
to:
 $AQUERY_TRANS_AFTER 
in:
 YLVPLNMSS_RSPE (line 80)

**Comment by kevmza** [comment]
Added YLVE to patch SRC_YSCSA_209_201801191444

**Comment by kevmza** [comment]
Patch available to be patched to NGATEST 

20180119_1444_SRC_YSCSA_209_KEMEY

**Comment by EmmanuelEdhedhe** [comment]
Completed
