### ISSUE TITLE
Exit notifications not going to all stakeholders

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/People-Connect#21]
Exit notifications are not being received by all stakeholders.  Please enable notifications as per attached list
[Exit Notification List.docx](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1457327/Exit.Notification.List.docx)

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=132 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
Message from @Adebukola : Exit notification is being received by only the Work Ethics group. Please ensure all exit stakeholders get exit notifications.

**Comment by Mandiklopper** [comment]
Detail from #58:

Exit notifications did not go to all exit stakeholders; specifically exitmanagement@ubagroup.com and exitissues@ubagroup.com. Please update notification with the groups in the attached document.
 All the stakeholders that have 'NO' on the clearance column should be able to view the feedback that other stakeholder with 'YES' have provided
 Contacts for the mailing lists are

Email Group Contact Person

workethicsteam@ubagroup.com - Gbenga Ogunleye, Enobong Egere
ITRegionalSupportHeadOffice@ubagroup.com - Joseph Akinwunmi
user_admin.ho@ubagroup.com - Sola Gbadamosi
itcare@ubagroup.com - Mistura Mohammed
itenterprisenetworks@ubagroup.com - Kemi Orimoloye
GroupRecoveryRemedialMgrs@ubagroup.com -Anike Isinguzo
CreditMonitoringGroup@ubagroup.com - Aina Ajibola
FraudPreventionInvestigationsGroup@ubagroup.com - Bukola Jaga
compliancehelpdesk@ubagroup.com - Robinson Imafidon
BranchSupportOPS@ubagroup.com - Olaniyi Lawal
CSFleet@ubagroup.com - Seidu Christy
Adegboyega.Adejuwon@ubagroup.com - Adegboyega Adejuwon
exitmanagement@ubagroup.com - Taiwo Ikuejurojo, Samvic Akinyemi
exitissues@ubagroup.com - Taiwo Ikuejurojo, Samvic Akinyemi

Exit Notification List.docx
[Exit.Notification.List.docx](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1478068/Exit.Notification.List.docx)

**Comment by Mandiklopper** [comment]
Logged against ticket:

Exit notifications did not go to all exit stakeholders; specifically exitmanagement@ubagroup.com and exitissues@ubagroup.com. Please update notification with the groups in the attached document.
 All the stakeholders that have 'NO' on the clearance column should be able to view the feedback that other stakeholder with 'YES' have provided
 Contacts for the mailing lists are

Email Group Contact Person

workethicsteam@ubagroup.com - Gbenga Ogunleye, Enobong Egere
ITRegionalSupportHeadOffice@ubagroup.com - Joseph Akinwunmi
user_admin.ho@ubagroup.com - Sola Gbadamosi
itcare@ubagroup.com - Mistura Mohammed
itenterprisenetworks@ubagroup.com - Kemi Orimoloye
GroupRecoveryRemedialMgrs@ubagroup.com -Anike Isinguzo
CreditMonitoringGroup@ubagroup.com - Aina Ajibola
FraudPreventionInvestigationsGroup@ubagroup.com - Bukola Jaga
compliancehelpdesk@ubagroup.com - Robinson Imafidon
BranchSupportOPS@ubagroup.com - Olaniyi Lawal
CSFleet@ubagroup.com - Seidu Christy
Adegboyega.Adejuwon@ubagroup.com - Adegboyega Adejuwon
exitmanagement@ubagroup.com - Taiwo Ikuejurojo, Samvic Akinyemi
exitissues@ubagroup.com - Taiwo Ikuejurojo, Samvic Akinyemi

Exit Notification List.docx

**Comment by Mandiklopper** [comment]
Completed.  Linked the Exit stakeholders.  Please retest.
