### ISSUE TITLE
Unable to Update and Create Func Hierarchical for positions.

### ISSUE THREAD

**Issue by bldre03** [Mandiklopper/People-Connect#212]
Dear Mandy,

Kindly assist to check the iniability to Update and Create Func Hierarchical for positions.

Please see error message below.

[F:YCTR] : Class Non-exstent.

Best Regards,

**Comment by jwvjaar** [comment]
Please provide me with position details, as I have tried to replicate the issue, but the changes were saved without any problems.

**Comment by jwvjaar** [comment]
Dear JW,

This has been resolved.

Best Regards,
Oyebola Owoseni   
HR Information System Administrator
