### ISSUE TITLE
Commendation notification list

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/People-Connect#23]
Commendation notifications should go to the stakeholders contained in attached list.
[Commendation Stakeholder List.docx](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1457422/Commendation.Stakeholder.List.docx)

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=138 - Not assigned on Senseable

**Comment by Mandiklopper** [comment]
Completed by Pierre.  Please retest.
