### ISSUE TITLE
CR:  Staff movement approval GMD

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/People-Connect#230]
Current Condition:
The current approval process for the GMD on Staff Movements is not followed as developed.  The GMD currently sends the approval by email to the GHHR and the SAGE Consultants needs to manually approve on the system.

Proposed Changes:
Develop a window where a proxy can approve on behalf of the GMD.

Change request emailed to @roberteta to sign off.

**Comment by jwvjaar** [comment]
implemented on PREPROD

Personnel administration > Staff movement > GMD staff movement approval

**Comment by Mandiklopper** [comment]
Change request signed off by Robert, Martin and Abiola.
