### ISSUE TITLE
CR:  Deletion of Staff Movement

### ISSUE THREAD

**Issue by Mandiklopper** [Mandiklopper/People-Connect#231]
Current Condition:
Staff movement transactions can only be cancelled before implementation.

Proposed Changes:
Cancelation option should include deletion of already created contracts as well as sending of notification if already implemented.

Change request sent to @roberteta

**Comment by Mandiklopper** [comment]
Signed off by Robert, Abiola and Martin.

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Cancellation of staff movement after implementation | Passed | Works as expected, no new contract and old contract has no end date.
Email sent to notify | Failed | No email is sent after cancellation.

**Comment by janwvjaarsveld** [comment]
Email notification has been fixed.

**Comment by janwvjaarsveld** [comment]
Patch 20180130_1220_YSCSA_#83_#231_JWVJA

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Email sent to notify | Passed | Works as expected, when a staff movement has been canceled, an email is sent to notify the employee that it has been canceled.

**Comment by Mandiklopper** [comment]
@Yinka123 please test
