### ISSUE TITLE
Content of Commendation Letter

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/People-Connect#24]
Template for commendation letter should be updated.  Attached is the one that was issues yesterday.  Changes are contained therein
[Issue with Content of Commendation Letter.docx](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1457490/Issue.with.Content.of.Commendation.Letter.docx)

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=139 - not yet assigned on Senseable

**Comment by Mandiklopper** [comment]
Closed by Pierre.  Please retest.

**Comment by janwvjaarsveld** [comment]
Stale ticket. Please re-open if this is still an issue
