### ISSUE TITLE
Default values on company screen

### ISSUE THREAD

**Issue by janwvjaarsveld** [Mandiklopper/People-Connect#246]
Add fields to the company screen to determine default parameters:

- GHHR directorate
- HRIS administrator position
- Leave admin position

**Comment by janwvjaarsveld** [comment]
Patch #246_COMPANY_FIELDS_20180124

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----------- | ---------- | ----------
Fields to determine parameters, GHHR, HRIS, Leave Admin | Passed | There are fields on the company screen to determine these parameters.

**Comment by Mandiklopper** [comment]
@Yinka123 please test

**Comment by Yinka123** [comment]
Pass

**Comment by Yinka123** [comment]
Yet to be patched to Test environment, nothing to test for now.

**Comment by Yinka123** [comment]
Passed on NGDEV2

**Comment by Yinka123** [comment]
Passed
