### ISSUE TITLE
Redeployment & Relief Assignment Stakeholder Notification List

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/People-Connect#25]
The list of people to get notification after the last approval for redeployment or relief assignment ae as contained in attached document.
[Redeployment_Relief Stakeholder Notification List.docx](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1457719/Redeployment_Relief.Stakeholder.Notification.List.docx)

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=136 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
Completed.  Please retest.

**Comment by roberteta** [comment]
Same as #2

The following stakeholders are not getting the staff movement notifications;

•	2nd level supervisors (both releasing and accepting)
•	Branch Managers(BM) for branch staff

This is based on review of sample email notifications sent out. See sample below

From: PeopleConnect
Sent: Monday, November 27, 2017 5:36 PM
To: Abdulganiyu, Bashir bashir.abdulganiyu@ubagroup.com
Cc: Oyewale, Abdulrasheed abdulrasheed.oyewale@ubagroup.com; Jamgbadi, Kayode kayode.jamgbadi@ubagroup.com; Abdul, Musa Musa.Abdul@ubagroup.com; Abbagana, Zainab zainab.abbagana@ubagroup.com; Payrollvalidation Payrollvalidation@ubagroup.com; User_Admin HO user_admin.ho@ubagroup.com; Mohammed, Mistura mistura.mohammed@ubagroup.com; Akinpelu, Comfort comfort.akinpelu@ubagroup.com; Adeyemi, Elisha elisha.adeyemi@ubagroup.com; Abdulkareem, Ahmed ahmed.abdulkareem@ubagroup.com; Sagay, Israel israel.sagay@ubagroup.com; Adeshina, Babajide babajide.adeshina@ubagroup.com; Are, Olasunkanmi Olasunkanmi.Are@ubagroup.com; ITCARE ITCARE@ubagroup.com; Oprisk Mgt Team opriskmgtteam@ubagroup.com; ConfirmationTeam ConfirmationTeam@ubagroup.com; Recordsteam recordsteam@ubagroup.com; Isioma-Nwaligbe, Soso soso.isioma-nwaligbe@ubagroup.com; UBAAcademy ubaacademy@ubagroup.com; Seidu, Christy Christy.Seidu@ubagroup.com; Chuks-Ngwu, Christie christie.chuks-ngwu@ubagroup.com
Subject: Relief Assignment A09630 - Abdulganiyu Bashir

Dear Abdulganiyu Bashir,

We are pleased to inform you of your Relief Assignment.Please find the details below:

DEPARTMENT/BRANCH: CMC/ZPC Gombe (BR381)
LOCATION: Biu Road ,Gombe (0303)
NEW JOB TITLE: Head Cash Management Center
NEW SUPERVISOR: Abdulrasheed Oyewale
EFFECTIVE DATE: Wednesday, 22 NOV 2017
COMPLETION DATE: Sunday, 03 DEC 2017

PREVIOUS SOL ID: 0303
PREVIOUS JOB TITLE: Cash Officer

You are expected to hand-over to the next line officer or your supervisor and report to your new supervisor on the Effective Date.
Please note that failure to resume at your new location on the effective date will amount to policy infraction.
We wish you the best in your new assignment.

Thank you.

Human Capital Management

**Comment by Mandiklopper** [comment]
Closed by Pierre.

**Comment by roberteta** [comment]
Branch Managers still not getting email notification for staff movement for Branch Staff.

Based on complaint by HRBP as per message below, attaching sample redeployment letters for the employees below

Dear Team,

We have received a couple of complaints from BMs on their non-inclusion in the recipient list for redeployments of Services staff.

Kindly assist to review further for subsequent processes.

- Redeployment of A11740 on 30/12/2017
- Redeployment of A19671 on 02/02/2018
-  Redeployment of A24297 on 12/01/2018

**Comment by janwvjaarsveld** [comment]
After moving to PROD, there was a period where the Entry point used to manage all additional WF recipients was not properly setup and only the approvers of the Staff movement + the employee received the notification.

We picked this up during the investigation of why certain stakeholders weren’t copied in the Disciplinary outcome notifications and it has been rectified about two weeks ago.

Please view sequence 1800038298 on the WFM, sent out this morning. The BM for this transaction is copied in the final notification.

**Comment by roberteta** [comment]
Following further complaints of BMS not getting notification when their staff are moved, I have reviewed a staff movement of a branch staff A09745 (Cash Officer) implemented on 01 March 2018 and below are my findings;

•	The cash officer position reports to the BOM position, so functional supervisor is the BOM
•	From sequence number 1800047944, 
o	The releasing BOM(functional supervisor) was not copied 
o	The receiving BOM (functional supervisor) was not copied
o	The releasing BM, Fortune Brume, was not copied
o	The receiving BM, Mcdreams Omoregbe was copied

The requirement is to copy the BMs as well as the 1st and 2nd level functional supervisors (releasing and receiving)

**Comment by janwvjaarsveld** [comment]
Is this item still an issue?

**Comment by janwvjaarsveld** [comment]
Stale ticket. Please re-open if this is still an issue
