### ISSUE TITLE
Content of sanction/ disciplinary notifications

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/People-Connect#26]
[Content of Notification of Suspension Pending Determination of Case.docx](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1457821/Content.of.Notification.of.Suspension.Pending.Determination.of.Case.docx)
The content of notification for disciplinary cases and sanctions should be the same as the letter templates earlier provided to the team.  The content of the email notification for  case against A20533 (suspension pending investigation)  logged yesterday did not have all the required details.  I have attached a sample letter for suspension pending investigation.  The areas highlighted in red are permanent and uneditable while the other parts will pull from the details entered into the system at time of logging the case.

Also looking at the wrong content going to the employee with letter of displeasure.

Please implement all letter templates as notifications for all other sanctions.

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=128 - Not yet assigned.

**Comment by Mandiklopper** [comment]
Yes, it has been patched to PREPROD on Wednesday 22 Nov

Please see ticket 254

**Comment by janwvjaarsveld** [comment]
Stale ticket. Please re-open if this is still an issue
