### ISSUE TITLE
Leave Plan

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#289]
Leave Plan 
1.	Currently: You can plan for some days off your entitlement, save and it gets approved 
Expectation: You must plan your complete/full entitlement days before you can save.  

2.	Currently: If you have plan for your Annual Leave and is approved for the female staff. You cannot modify and add another line to plan for your Maternity leave nor can you also create a new/separate plan for you Maternity Leave 

You can only have one plan per year. 

**Expectation:** Employee should be able to add a line and Plan for Maternity leave under the annual leave plan 
Exception should be given to the female employee to plan for their Maternity leave as it might happen during the course of the year.

**Comment by janwvjaarsveld** [comment]
Please test on PREPROD.

**Comment by EmmanuelEdhedhe** [comment]
@janwvjaarsveld  Tested on PREPOD it Okay

Please replicate patch  on PROD

**Comment by EmmanuelEdhedhe** [comment]
Please confirm patch on PROD So i can close this ticket

**Comment by janwvjaarsveld** [comment]
Confirmed
