### ISSUE TITLE
Warehoused Leave day credit 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#291]
1.	Expectation: All approved warehouse leave days gotten by approval off the system will be credited to the employee WH approved leave heading only by the leave admin. 

No credit to Annual Leave days

**Comment by NicSmit** [comment]
Heading:
LVEWHFRPEN - Warehoused Leave Pending to Authorized WH leave totals
This Heading posts a variable entry to the Warehouse leave totals adding to the accrued and then deducting that same amount of days from the Pending balance.
Variable:
V_WHLVEPTA - Variable entry from Pending to Warehouse

**Comment by NicSmit** [comment]
Chidi, can you please look at the Access part to make sure that only leave admins can perform this function

**Comment by EmmanuelEdhedhe** [comment]
Completed
