### ISSUE TITLE
Access to Civil Status Tab on Employee Screen

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#295]
The current approval requirements on Employee updates via ESS and the present challenge on ESS requires that the Employee services team be given access to perform updates to hospital of employee/spouse /dependants and also addition of dependants.

Based on the above please include edit rights on the civil status tab of the employee screen and add the following persons to the ‘Team Member HCM Operations – Employee Services’ role;

1.	Taiwo Ikuejurojo
2.	Lorine Felix-Michael

**Comment by Mandiklopper** [comment]
@chidiif  please look into this.

**Comment by chidiif** [comment]
Done.
