### ISSUE TITLE
Resumption Screen 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#310]
1. A column for EXPECTED RESUMPTION DATE should be included and NOT EDITABLE

2. Expected  Resumption Date should be beside the RESUME ON field     Also if the RESUME ON DATE IS NOT EQUAL TO Expected Resumption date, THEN   the COMMENT FIELD SHOULD BE MANDATORY ELSE the comment field need not be compulsory

3. Incorrect/ Unclear Leave type column ("Initial " should be removed, The Nature of Absence field should be renamed to "Leave Type"

![g](https://user-images.githubusercontent.com/34434368/36253187-821f5284-124f-11e8-9f07-65ab3f9963f9.png)

**Comment by janwvjaarsveld** [comment]
@EmmanuelEdhedhe This has been completed and patch to PROD. Please confirm and close

**Comment by EmmanuelEdhedhe** [comment]
Confirmed Closed.
