### ISSUE TITLE
WF- Email Notification Requester & Recipient address 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#311]
Email   Notification: Requests To Make You Relief & Leave Resumption Date 

Current:   Dear ...,     Peter Iserhienrhien Requests To Make You Relief     This is to inform you .... **You are expected to login   People Connect to** …... to respond to the request.         

EXPECTED: Dear   ...,     Peter Iserhienrhien Requests To Make You Relief     This is to inform you .... **you are expected to login to People Connect to** …... to respond to the request....

![g1](https://user-images.githubusercontent.com/34434368/36253703-022be77a-1251-11e8-83fd-9652410b53bc.png)

**Comment by P1errevanZyl** [comment]
20180221_1434_PVZ_311_Leave notifications_YSCSA

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----- | ----------- | -------------------
Resumption email | Passed | Works as expected, does exactly what is asked. Has leave type, amount of days, day of return and actual resumption.

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----- | ----------- | -------------------
User logged and Dear "user" is NOT the same | Passed |  Dear (supervisor), LOGGED BY "user:, it is now different and not all the names are the same anymore. (Highlighted in Yellow)
Relief email notification message | Failed | no email for relief was sent out.

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----- | ----------- | -------------------
Relief email notification message | Passed | Works with correct message "You are expected to login to People Connect to"

**Comment by EmmanuelEdhedhe** [comment]
@janwvjaarsveld Please confirm if this has been patched oN PREPOD & PROD

**Comment by EmmanuelEdhedhe** [comment]
Tested on PREPOD - PASS

Please confirm patch onto PROD and close ticket

**Comment by P1errevanZyl** [comment]
Patched to PROD
