### ISSUE TITLE
WF - Resumption Notification 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#312]
1. NOTIFICATION   EMAIL SHOULD  GO TO ALL STAKEHOLDERS- Initiator, Supervisor and LEAVE MANAGEMENT TEAM alone.   NOTE:  The Leave management team should be included only when the supervisor has approved the Leave resumption

2. The supervisor must get a WF approval request for resumption after the employee logs resumption. 

3. Monthly   notification to be sent to those that should have resumed but have not yet recorded as having resumed on the system  “- Reg. 063   in BRD

**Comment by P1errevanZyl** [comment]
20180226_0946_PVZ_312_Resumption Notification

Please add Stakeholder Group 21 manually in the Others table on workflow YDCGSRDRC

Test Worflows:
YDCGSRDRN
YDCGSRDR
YDCGSRDRC
YDCGSRDCH

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----- | ----------- | -------------------
Resumption Notification | Passed | Works as expected 
Resumption Reminder | Passed | Works as expected

**Comment by EmmanuelEdhedhe** [comment]
@P1errevanZyl @janwvjaarsveld  Has this been completed and patched onto PREPOD & PROD?.

**Comment by janwvjaarsveld** [comment]
has this been tested?

**Comment by EmmanuelEdhedhe** [comment]
@janwvjaarsveld  This has been tested on PREPOD. Kindly patch onto PROD

![image](https://user-images.githubusercontent.com/34434368/38805980-1ed7aee4-4178-11e8-810a-b790607a9762.png)

![image](https://user-images.githubusercontent.com/34434368/38805987-21de154c-4178-11e8-9393-9eacfbdaa235.png)

**Comment by EmmanuelEdhedhe** [comment]
@janwvjaarsveld  This has been tested on PREPOD. Kindly patch onto PROD

![image](https://user-images.githubusercontent.com/34434368/38805980-1ed7aee4-4178-11e8-810a-b790607a9762.png)

![image](https://user-images.githubusercontent.com/34434368/38805987-21de154c-4178-11e8-9393-9eacfbdaa235.png)

**Comment by EmmanuelEdhedhe** [comment]
Is No 3requirement  Ready ?
Monthly notification to be sent to those that should have resumed but have not yet recorded as having resumed on the system “- Reg. 063 in BRD

**Comment by P1errevanZyl** [comment]
Patched to PROD
