### ISSUE TITLE
Email Notification - Upcoming planned leave MAT

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#316]
Include   EDD (Expected Due Date) in the email notification

**Comment by P1errevanZyl** [comment]
20180222_1648_PVZ_316_318_Leave WF formats

Please test the following Workflows to confirm the EDD is included when MAT leave is selected.

XDCGFYI
XDCGAUTRUI
XDCGMOD
XDCGMODRF
XDCGMODVS
YDCGMLREM1
YDCGMLREM2
YDCGMLREM3
YDCGREMIN1
YDCGREMIN6
YLVPLNAPR
YLVPLNREF
YLVPLNVIS

**Comment by janwvjaarsveld** [comment]
@EmmanuelEdhedhe has this been tested?

**Comment by ArmandCtz** [comment]
Test | Passed/Fail | Comment/Finding
----- | ----------- | -------------------
Include EDD | Passed | All workflow messages work and has the added EDD in the email notification.

**Comment by NicSmit** [comment]
The last comment on this ticket is ready to patch to test... Can we please get an update on the current status of this ticket?

**Comment by P1errevanZyl** [comment]
Patched to PROD
