### ISSUE TITLE
Leave Advice notification

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#317]
Should   include the number of outstanding days ( Req. 002 in BRD)

All leave advice to staff should show the number of outstanding annual leave days after taking into account the current leave being advised

**Comment by EmmanuelEdhedhe** [comment]
Still pending

**Comment by P1errevanZyl** [comment]
Changes was made and tested

Patch below

20180405_1002_PVZ_317_Leave advice notification

**Comment by EmmanuelEdhedhe** [comment]
Tested on PREPOD = PASS

Please patch into PROD

**Comment by EmmanuelEdhedhe** [comment]
Confirm if this have been patched onto PROD

**Comment by janwvjaarsveld** [comment]
confrimed
