### ISSUE TITLE
Leave Notifications

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#318]
1. All   notifications should be formatted to ensure that the dates are on a new line   e.g.      Commencement Date: Monday, 12 February 2018 Completion Date: Thursday, 15   February 2018     Expected Resumption Date: Friday, 16 February 2018     Actual Resumption Date:13/02/2018 

2. Consitent  Date format should be adapted   Some notifications have "Friday, 16 February 2018"  ( e.g. Leave Request) while others   16/02/2018 (e.g. Leave Resumption) and others mix various formats ( Leave   Resumption, Leave Plan etc)
--

![g3](https://user-images.githubusercontent.com/34434368/36255691-b2dc594a-1258-11e8-9467-9abdbd199418.PNG)

**Comment by P1errevanZyl** [comment]
20180222_1648_PVZ_316_318_Leave WF formats

Please test all the workflows listed below

XDCGFYI
XDCGAUTRUI
XDCGMOD
XDCGMODRF
XDCGMODVS
YDCGMLREM1
YDCGMLREM2
YDCGMLREM3
YDCGREMIN1
YDCGREMIN6
YLVPLNAPR
YLVPLNREF
YLVPLNVIS

**Comment by EmmanuelEdhedhe** [comment]
Completed
