### ISSUE TITLE
Incomplete updates to X3 Employee records with approved ESS change requests

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#337]
Some requests to update employee’s details via ESS do not update the records on X3 even after approval by Supervisors and HRBPs. 

This is very worrisome and gives me serious cause for great concern.

The example below is a case in point that should be investigated as a matter of urgency.

I have painstakingly reviewed ESS workflow monitor records to extract details of change requests that were made and approved (between 15 & 17 January, 2018) and reviewed these against the employee’s record of the staff in question –A20801.

The following WFM sequence numbers of 15th February, 2018, reviewed did not completely update the employee's record on X3;

- 1800008129 (15 Feb)
- 1800008130 (15 Feb)
-1800008132 (15 Feb)
-1800008306 (15 Feb)
-1800008316 (15 Feb)
-1800008340 (15 Feb)
- 1800008341 (15 Feb)
-1800008343 (15 Feb)
- 1800008351 (15 Feb)
-1800009998 (16 Feb)
-1800010026 (16 Feb)

Regards,

**Comment by Pappabeer** [comment]
Jan Willem responded and will look into this in the morning

**Comment by janwvjaarsveld** [comment]
The only item that is not yet implemented is sequence 1800009998 and 1800010026 as they have not yet been approved by the supervisor

**Comment by Pappabeer** [comment]
Does  the mean we can close the ticket?
