### ISSUE TITLE
Editable grade field in Appointment Staff Movement

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#356]
The grade field is editable during an appointment staff movement. The only time when the grade field should editable is for a ‘promotion’ staff movement

**Comment by janwvjaarsveld** [comment]
Please provide the steps taken. Grade field is only editable for promotion during testing on PROD.

**Comment by roberteta** [comment]
Steps taken by A23512 are as follows;

1. Staff Movement > Singe Processing
2. Seelect Employee ID and current details defaults
3. In the Staff Movement details section, select Appointment as reason for movement and then select effective date
4. In the New details tab, the following fields are available for data selection - Directorate, Division, Department/Branch, Position and GRADE.
5. The Grade field is active and blank, and clicking on the magnifying glass opens up a page with all the grades mapped to the selected position.

**Comment by janwvjaarsveld** [comment]
This helped a lot. Issue has been resolved.

**Comment by roberteta** [comment]
Confirmed resolved.
