### ISSUE TITLE
Non receipt of Sanctions WF notifications IRO Cases 188, 189 & 190

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#358]
There is evidence of these WFs in the WF monitor, but checks with various stakeholders (Initiator, Work Ethics team & HRBP) reveal that none of them got any of these email notifications

**Comment by janwvjaarsveld** [comment]
Workflows has been resent. Please confirm reciept

**Comment by roberteta** [comment]
Confirmed
