### ISSUE TITLE
Error on Approving Initiated Staff Movement for Head Teller Position

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#36]
![error on approving relief assignment](https://user-images.githubusercontent.com/33485868/32648131-bdaab46c-c5f4-11e7-955e-3f7e0e7c3495.jpg)

Attempts to approve Relief Assignment for A11281 came up with the error message in the attached  message '**This is a redeployment transaction and at least the position must updated'**

1. The error message should be corrected for grammer as follows 'This is a Relief transaction and at least the position must be updated'**

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=130 - Not assigned yet on Senseable.

**Comment by Mandiklopper** [comment]
Local menu 6955 line 17 has been updated with: 'This is a Staff Movement transaction and at least the position must be updated'.  Please test
