### ISSUE TITLE
Non receipt of exit request email notification by Exit Management Team

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#360]
Following exit request by Staff, subsequent interview and processing by HRBP and comments by Supervisor, the Exit Management team does not get any notification for their action to enable exit checklist notification to be be sent to exit stakeholders.

An example is that of employee A00610

**Comment by roberteta** [comment]
@MartinKruger , What is the update on this request?

**Comment by janwvjaarsveld** [comment]
A recurring task has been scheduled to sent out the notification 24hrs after the request has been approved by the HRBP, as per the BRD. 
A manual WF has also been created and the notification was sent out to the Exit management team for all employees whos request has been approved, but contract is still active (Final exit not checked).
