### ISSUE TITLE
WF - Leave Plan Initiation Request 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#361]
1.  Include a link that will direct the recipient to the point where the action is required

2.  Include a call to action 

![image](https://user-images.githubusercontent.com/34434368/37293077-fca11d92-261a-11e8-9604-7d1f1c29da10.png)

**Comment by janwvjaarsveld** [comment]
Completed on PREPROD, please test.

**Comment by EmmanuelEdhedhe** [comment]
Tested. Please patch onto PROD
![image](https://user-images.githubusercontent.com/34434368/37648108-ab6faad4-2c36-11e8-88ae-039554a35204.png)

**Comment by EmmanuelEdhedhe** [comment]
Has this been patched onto PROD?

**Comment by EmmanuelEdhedhe** [comment]
Tested on PREPOD = PASS.

Please confirm patch onto PROD and close ticket

**Comment by P1errevanZyl** [comment]
Patched to PROD
