### ISSUE TITLE
Faulty Recipient for Final Exit Notification

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#364]
Final exit notifications for A03554, A05733, A20275 (branch staff), are being sent to HRBP in Head Office (A21537) and A22454 (Corporate HR Specialist - Talent Mgt) (who has HRBP TL role for purpose of approving  Appointment staff movement loaded by HRIS Administrator).

The other/relevant HRBPs are not getting the notifications.

Please urgently investigate and fix this issue

**Comment by roberteta** [comment]
HRBP Team Lead A21537 is getting 4 final exit notification for the same employee

**Comment by janwvjaarsveld** [comment]
As far as I can see this had to do with the blank contract that was still on the system last week. The workflow codes that sent to these employees are the second level supervisors of the admin supervisors, which were all occupied by the blank employee number. With the deletion of the blank contract, this should no longer occur on the system
