### ISSUE TITLE
Issues with Consultant Grade selection on Employee Arrival screen

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#365]
On the arrival screen /contract tab, attempts to select a Consultant grade for a new hire is not possible as the selection defaults to either NSP grade or UBA Intern grade. See examples below where for the positions below selection of Consultant grade from the drop down menu defaults to the grade shown

J0211099901812 defaulted to UBA Intern
J0211099901814 defaulted to NSP

**Comment by roberteta** [comment]
Please this is holding back the onboarding of a new hire as consultant

**Comment by roberteta** [comment]
Additional information:
1. The standard job for this new hire is Relationship officer 
2. This standard job has been updated to accept grade from Consultant to SBO
3. For positions linked to this standard job, need to also be updated to accept grades from Consultant to SBO
4. Attempt to update the position grade information by selecting consultant from the drop down menu, defaults to NSP.
5. Please urgently look into this urgently
6 . We are considering the alternative of  onboarding the new hire with BO grade today and subsequently get your help to change the grade to consultant from the back-end when this issue is resolved.

**Comment by janwvjaarsveld** [comment]
Object selection index was set on SEQ, but since the sequence number for NSP, INT, CON are all blank, upon selection the system had no way of identifying the correct code. The index has been set to SEQ+COD, which solved the problem.
