### ISSUE TITLE
GHHR Feedback on Staff Movement awaiting Management Approval

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#40]
Please see below feedback from the GHHR on Staff Movement awaiting Management Approval;

1.  There should be a column to see who is requesting for the Staff Movement Approval (i.e. the HRBP Team Lead's name)

2. There should be a column named justification where the justification for the Movement should be captured  by the HRBP Team lead

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=133 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
Closed by JW. Please test.
