### ISSUE TITLE
Maternity Leave days Incorrect Number of days Calculation

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#410]
Applied for Exact 60 working day equivalent of 12 week.

But the system calcualet teh toatle numbe rof days to be lower or more than 60 days. 
System automatically increase the end date and alter the toatl number of days. 

![image](https://user-images.githubusercontent.com/34434368/38565677-34383fdc-3ce2-11e8-8c98-a1f1f2976d7f.png)

**Comment by NicSmit** [comment]
after discussion with Dev, the following conclusion was reached. When entering Maternity leave plan. the user should enter the start date and then tab through the fields, the system will then auto populate the end date exactly 60 days from the start date. If you enter the end date the system goes into a loop and recalculates, therefore you get the incorrect number of days. therefore, do not enter an end date for maternity leave

**Comment by EmmanuelEdhedhe** [comment]
Tested working as stated.
