### ISSUE TITLE
PREPROD/PROD Accepted leave transaction still Stay on Pending leave transaction Block 

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#416]
Already approved leave transaction stays on the pending leave transaction 

**Expected:** Accepted or approved leave leaves the pending leave transaction block and moves to the Leave history Block 

![image](https://user-images.githubusercontent.com/34434368/38940082-aab6118c-4329-11e8-9eb0-e5275af3b77e.png)

**Comment by EmmanuelEdhedhe** [comment]
Please has this been looked into?

**Comment by EmmanuelEdhedhe** [comment]
This issue still persists. 

Please, when will this be resolved?.

**Comment by janwvjaarsveld** [comment]
fixed. please test.

**Comment by EmmanuelEdhedhe** [comment]
Tested on PREPROD - OKAY.

Please replicate on PROD and close ticket.
