### ISSUE TITLE
PROD- Leave Type Not Visible When Leave Admin enter leave onbehalf of an Employee

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#418]
When the leave admin enter leave transaction on behalf of an employee

On the employee ESS screen, the leave type field will be empty it won't show the leave type but show the start and end date

![image](https://user-images.githubusercontent.com/34434368/38940795-5464461c-432b-11e8-9267-4d094637f1d9.png)

**Comment by EmmanuelEdhedhe** [comment]
Please, can someone look into this?

**Comment by janwvjaarsveld** [comment]
Captured leave on Entry of Absence, leave type is showing on Resumption. Please give the data to test your issue.
![capture](https://user-images.githubusercontent.com/29533672/39193576-2e83142c-47dc-11e8-8bf7-5ff5d5856a7c.JPG)

**Comment by EmmanuelEdhedhe** [comment]
Ran a test now and its working as expected.

**Comment by janwvjaarsveld** [comment]
Did not change anything, so must have been an user error.
