### ISSUE TITLE
WF- Course of study approval- Incomplete message to GHHR | PROD

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#419]
1. Message incomplete as thus:

Dear Patricia Aderibigbe

Study course: EEC 501
Course description: Electronics

Thank you. 

![image](https://user-images.githubusercontent.com/34434368/38943169-07857ba8-4331-11e8-881a-4056391c9878.png)

2. Secondly: The approval goes into a loop without a final staus asn the GHHR is the final approval 

3. No call to action 

4. No attachment

**Comment by EmmanuelEdhedhe** [comment]
Expexted WF with call to action link 
![image](https://user-images.githubusercontent.com/34434368/38943484-d1ed774c-4331-11e8-8200-13ef747ebee2.png)

**Comment by janwvjaarsveld** [comment]
please test on PREPROD

**Comment by EmmanuelEdhedhe** [comment]
**Tested PASS- Number 1,2, & 4**

![image](https://user-images.githubusercontent.com/34434368/39049997-ed9af0a0-44a3-11e8-9f46-68a804d17c57.png)
 

**Number 3 - FAIL** 
Please include the call to action and link to PeopleConnect

![image](https://user-images.githubusercontent.com/34434368/39050022-0c26f67c-44a4-11e8-9660-71e38096b05e.png)

**Comment by janwvjaarsveld** [comment]
Please email me the signed off CR

**Comment by janwvjaarsveld** [comment]
Test on PREPROD

**Comment by janwvjaarsveld** [comment]
made a rookie mistake, fixed now

**Comment by EmmanuelEdhedhe** [comment]
Confirmed Okay.

Please patch to PROD and close ticket

**Comment by janwvjaarsveld** [comment]
patched
