### ISSUE TITLE
Approval scenarios- Supervisor on Leave and relief is operational

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#420]
3.	We also need to test the integration between leave management and core HR especially in the areas of how ESS updates awaiting supervisor approval will be handled when the supervisor is on leave and a relief is operational for such supervisors, also how will staff movement notifications that should go to supervisor be handled when the supervisor is on leave and a relief is operational.

**Comment by janwvjaarsveld** [comment]
This is functional testing. Please only assign dev tickets to us.
