### ISSUE TITLE
Relief Selection Prioritizing ESS

### ISSUE THREAD

**Issue by EmmanuelEdhedhe** [Mandiklopper/People-Connect#423]
In the instance, there is a relief clash or an employee need to select the second relief it pulls all the employee instead of the employee 2 approved relief 

**Expectation:** It show lookup only the two approved relief for selection

![image](https://user-images.githubusercontent.com/34434368/39038098-e94180b2-4482-11e8-81e1-342c988974e3.png)

![image](https://user-images.githubusercontent.com/34434368/39038111-f611ce28-4482-11e8-98b6-f2d273cc2de7.png)

**Comment by EmmanuelEdhedhe** [comment]
On Both PREPROD and PROD

**Comment by janwvjaarsveld** [comment]
resolved
