### ISSUE TITLE
Exit stakeholder unable to save exit checklist

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/People-Connect#46]
IT Care exit stakeholder was unable to save exit checklist that she completed.  The message ' transaction stopped on saving key A23237 A23237NG001 04/08/2014 in table YEMPLOCTRESS (Obsolete record)' came up when the save button was clicked

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=140 - Not yet assigned on Senseable

**Comment by Mandiklopper** [comment]
Kiran message:  
I think what happened is that some changes were made on the end tab, if they reverse the termination then we clear the termination checklist table for that termination.  So I think while the person was doing their checklist, exit management, reversed the termination and the records the person was working on was deleted.

@Adebukola and @roberteta  please check with the team if the above was the case?

**Comment by janwvjaarsveld** [comment]
Stale ticket. Please re-open if this is still an issue
