### ISSUE TITLE
Exit Notifications Not Going Through & Non Clearing Stakeholders To View Clearance List

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/People-Connect#57]
Exit notifications did not go to  all exit stakeholders; specifically exitmanagement@ubagroup.com and exitissues@ubagroup.com.  Please update notification with the groups in the attached document.
All the stakeholders that have 'NO' on the clearance column should be able to view the feedback that other stakeholder with 'YES' have provided
Contacts for the mailing lists are 

Email Group	                                       Contact Person
 	 
workethicsteam@ubagroup.com  - Gbenga Ogunleye, Enobong Egere
ITRegionalSupportHeadOffice@ubagroup.com - Joseph Akinwunmi
user_admin.ho@ubagroup.com - Sola Gbadamosi
itcare@ubagroup.com - Mistura Mohammed
itenterprisenetworks@ubagroup.com - Kemi Orimoloye
GroupRecoveryRemedialMgrs@ubagroup.com -Anike Isinguzo
CreditMonitoringGroup@ubagroup.com - Aina Ajibola
FraudPreventionInvestigationsGroup@ubagroup.com - Bukola Jaga
compliancehelpdesk@ubagroup.com - Robinson Imafidon
BranchSupportOPS@ubagroup.com - Olaniyi Lawal
CSFleet@ubagroup.com - Seidu Christy
Adegboyega.Adejuwon@ubagroup.com - Adegboyega Adejuwon
exitmanagement@ubagroup.com - Taiwo Ikuejurojo, Samvic Akinyemi
exitissues@ubagroup.com -  Taiwo Ikuejurojo, Samvic Akinyemi

[Exit Notification List.docx](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1471724/Exit.Notification.List.docx)

**Comment by Mandiklopper** [comment]
Logged against Ticket 21.  Closed this one.

**Comment by Adebukola** [comment]
Not all stakeholders are getting notification of final exit.  Taiwo Ikuejurojo did not get notification of exits logged today, Nov 17, 2017

**Comment by Mandiklopper** [comment]
The correct email addresses were allocated.  Please advise if this is still the case @Adebukola
