### ISSUE TITLE
MSS Approval feedback from GHHR

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#62]
There is no information on the current details of the employee on the MSS approval grid.

Plese include 'old dept./branch', 'old location', & 'old position'.

**Comment by Mandiklopper** [comment]
Logged on Senseable on ticket: http://senseable.co.za/scp/tickets.php?id=133 - Assigned to JW.

Please also look at this message received from the GHHR as important:

There is no information on the current details of the employee on the MSS approval grid.

Please include 'old dept./branch', 'old location', & 'old position'.

Mandi message:
As discussed yesterday with the previous request logged there should just be a column with previous approver name and surname.
