### ISSUE TITLE
Multiple Staff Movement Requests with same details

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#63]
HRBP TMs and Employees are able to lod multiple staff movement request with the same details and this is accepted by the system. The reason for this is that they do not see the message at the top that says record created and so they load it multiple times.

Multiple staff movement requests with the same details should not be possible.

**Comment by Mandiklopper** [comment]
@roberteta this will be a change request.  We can then look at when we can complete the change request.

**Comment by roberteta** [comment]
@ Mandi,
I dont understand why this is a change request. According to me it is a system gap just the same way that the system allows the addition of the dependant with the same details multiple times via ESS and sends multiple workflows to the supervisor for approval

**Comment by jwvjaar** [comment]
Implemented on PREPROD for both X3 and ESS
