### ISSUE TITLE
MSS- Supervisor unable to enter comment on Exit Request

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/People-Connect#69]
Comment box for supervisor to enter comment for exit request is not allowing entries.  Screen shot is attached.
![img_0158](https://user-images.githubusercontent.com/33485745/32944078-88a51b1e-cb8e-11e7-96e6-8d828c5de84e.JPG)

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=163 - Not yet assigned on senseable.

**Comment by Mandiklopper** [comment]
The HRBP first needs to go into this transaction and add the interview date and follow the steps as on how to video.  Print screen of the request not completed by the HRBP attached.
![mss exit req](https://user-images.githubusercontent.com/33479066/33012516-d9d064fa-cde9-11e7-9f4e-29632921ed49.PNG)

**Comment by Adebukola** [comment]
Thanks Mandi.  Just going to raise a ticket now that HRBP is unable to enter date and interview status in the screen above.  It is only the comment box that is responsive right now.
Also, as per notification, only HRBPs need to be notified when employee logs exit request.  Supervisors are not to get the request until HRBP works on it.  Right now, supervisors get the request once employees log the request

**Comment by roberteta** [comment]
HRBP is able to enter date ,interview status and comments. To confirm that they are not able to update other areas prior to closing this
