### ISSUE TITLE
Request to Update Empl IDs for Promoted GT2 staff 

### ISSUE THREAD

**Issue by bldre03** [Mandiklopper/People-Connect#82]
Dear Mandy,

Attached is the list of staff whose Empl IDs are to be updated due to promotion.

Kindly advise on how to achieve this update on PeopleConnect.

Best Regards,
[Data for Empl IDs Update.xlsx](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1488653/Data.for.Empl.IDs.Update.xlsx)

**Comment by Mandiklopper** [comment]
@bldre03, this can be done by changing the key of the employee code.  

Go to Personnel Administration > Employees > Go to the employee >  On the right hand side click on Utilities, click on Change key > Type in the new employee code.  Then click on OK.

We have closed data migration and for control purposes SAGE can not update this list.  Just make sure when you start with the A number that it starts with the next number after the last A number on employees.

I am closing this ticket but please email me if need any assistance.

**Comment by roberteta** [comment]
@ Mandi, This steps only addresses the change in employee ID from CE to A.  The grade of these employees need to be changed as wel. Will this be via Promotion  action?

**Comment by Mandiklopper** [comment]
@bldre03 you will need to load the action of grade changes via the staff movement screen as promotion. 
I am going to close this ticket but please let me know if you need assistance.

**Comment by roberteta** [comment]
@ Mandi, he has already processed this as staff movement with reason as Promotion and redeployment notification was sent to his supervisor. But his supervisor Ugochi Okafor is not a HRBP Team Lead and so is unable to approve the transaction.

I believe that Staff Movement screen was developed with HRBP team members /team leads in mind.....but promotion is not handled by HRBPs.

Please confirm this from JW and revert

**Comment by Mandiklopper** [comment]
@roberteta, just to check.  With normal promotions who will do it.  If we look at promotions where it's not the bulk like with these transactions? Both single Promotions and bulk promotions have been build to be initiated by the HRBP.  Weren't the HRBP's suppose to do the promotion staff movements for these employees.

**Comment by roberteta** [comment]
Mandi, during the show and tell sessions this was discussed and it was stated that HRBPs do not handle promotions be it single or bulk. It is handled by the Career Management team. The HRIS Administrator loads the request for promotion and it is approved by the Head of Career Management.

For the bulk promotions that are the outcome of appraisal recall that we asked for a bulk upload feature where this can be loaded via excel by the HRIS Administrator and it is approved by the Head of Career Management. We expect that this will be delivered as part of the Performance Module

**Comment by Mandiklopper** [comment]
@roberteta  and @bldre03, I had a look at the system and it seems like the employee codes were not yet changed and the promotions were also not loaded yet.  Did discuss with JW and he advised that it will not cause issues.  Please continue.

Yes with bulk promotions we will look at it with Performance Management.

**Comment by roberteta** [comment]
@ Mandi, I dont understand what you mean by continue. The transaction has already been cancelled in the staff movement screen.

Are yu saying that the HRIS Administrator can change the employee ID using the guide you provided and then load these as staff movement selecting reason for movement as promotion?

**Comment by Mandiklopper** [comment]
@roberteta yes that is correct.  Change the employee id's and then do staff movement selecting promotion.

**Comment by roberteta** [comment]
@ Mandi / JW,

This Promotion staff movement has been loaded again and WF sent to approver. But attempt to approve came up with the message ' This is a staff movement transaction and at the position has to be updated'

Please note that promotion staff movement does not require a position change.

**Comment by Mandiklopper** [comment]
https://senseable.co.za/scp/tickets.php?id=220 - Logged on Senseable not yet assigned.

**Comment by Mandiklopper** [comment]
Completed.
