### ISSUE TITLE
ACCESS/ERRONEOUS CHANGE OF STAFF GRADE

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#83]
It may appear that the change is grade  of employee  A07498 from BO to BT1 may have been in error at the point of Relief Assignment processing by HRBP Team member.

1. Please disable access to change employee grade from all Staff Movement reasons apart from Promotion.

2. HRBP Team member and Team Lead should not have access to the promotion staff movement reason

3. The promotion staff movement reason should only be available to the HRIS Administrator profile.

**Comment by Mandiklopper** [comment]
@chidiif please assist

**Comment by Mandiklopper** [comment]
@chidiif  any update on this?

**Comment by chidiif** [comment]
@MartinKruger, Kindly assist to look at this case. My assessment is that it will require some development

**Comment by janwvjaarsveld** [comment]
Patch 20180130_1220_YSCSA_#83_#231_JWVJA

**Comment by Mandiklopper** [comment]
@Yinka123 please test.

**Comment by Yinka123** [comment]
Pass
