### ISSUE TITLE
MARITAL STATUS UPDATE ON EMPLOYEE SCREEN

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#86]
The new employees loaded on the Arrival screen by Mandi on 14th November, all defaulted 'Common Law' as marital status and  'African Traditional' as Religion.

Attempts by HRBP Team Lead to update the marital status from Custom  Law to Single displays 'record has been modified' message, but on exiting the screen this record reverts to Commin Law.

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=200 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
Closed by JW.
