### ISSUE TITLE
PROBATION PERIOD IS AFFECTED BY STAFF MOVEMENT FOR CURRENT CONFIRMED STAFF

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#87]
A reassignment action performed to move a staff from a wrong position J0724016800004 to a correct position J0718016800004 updated the probation period in the employee's contract screen. It sets the probation period as the contract date plus 6 months

See details below;

1. A02510 - Probation period on Employment contract screen updated to 23/05/2018 based on a Reassignment done today 23/11/2017

**Comment by Mandiklopper** [comment]
@roberteta what is the actual resumption date for that correct position.

**Comment by roberteta** [comment]
@ Mandi, The correct resumption date should be the date included in the employee take-on data for this staff

**Comment by roberteta** [comment]
02/05/2000

**Comment by Mandiklopper** [comment]
@roberteta I looked at the contract for the employee and it seems like the original contract with resumption date 02/05/2000 does not show.  Only a contract with resumption date 23/11/2017.  Did you use the reassignment option on staff movements when making then change?

**Comment by roberteta** [comment]
@ Mandi,

Jacquelyn made the change on the employment cntract and when prompted, she selected reassignment as reason

**Comment by Mandiklopper** [comment]
@roberteta reassignments must also be completed using the Staff movement option.  Reason for Movement:  STR14 - Reassignment.  This way the original contract will still be in place and a second contract will create.

**Comment by roberteta** [comment]
@ Mandi,
This will be a distortion of the career history of this person. The desire is not to create a new contract, and also loading as staff movement will send out notifications to the staff who is an Executive (GM grade).

Can this not be corrcted using the  export/import templates? Please confirm

**Comment by Mandiklopper** [comment]
@roberteta currently that is the way it was linked.  Even if we do it directly on the contract it will need to be a new contract.  If not, there will never be a record of the original start date of the contract.  This will also mean that the anniversary dates etc will change.  In the HR admin template with data provided Reassignment was one of the redeployment reasons and that is how the system has been configured.  It will be a Change request if we need to change this configuration.  Please advise

**Comment by roberteta** [comment]
@ Mandi,
Can this not be corrcted using the export/import templates? Please confirm

**Comment by Mandiklopper** [comment]
@roberteta it can be corrected with the import template but not the right way to do it.  A new contract needs to be created.  That is the process that needs to be followed for Reassignments.

**Comment by roberteta** [comment]
@Mandiklopper You dont seem to understand what gave rise to this transaction and why reassignment was used. I fully understand the staff movement reassignment, but this was not meant to be a reassignment but an action to correct an anomaly.

**Comment by janwvjaarsveld** [comment]
Stale ticket. Please re-open if this is still an issue
