### ISSUE TITLE
HRBPs Challenge  'Awaiting My Action' filter on Staff Movement Single Processing

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#90]
HRBP Team Leads are unable  to treat items showing under 'Awaiting my action’. 

They can view them but have to go back to ‘Awaiting HR action’ to treat them…… This is not convenient and efficient and defeats the purpose of asking for this filter

**Comment by Mandiklopper** [comment]
https://senseable.co.za/scp/tickets.php?id=203 - Not yet assigned on senseable.

**Comment by Mandiklopper** [comment]
Closed by JW.

**Comment by roberteta** [comment]
Issue remains unresolved. 

See feedback from a HRBP Team Lead (A00526);
'I have tried verification from ‘awaiting my action’ section but it was not successful; i.e., entries were only available for viewing.

I still had to go to back to the awaiting HR action to treat them'

Please look into this further.

**Comment by jwvjaar** [comment]
Please confirm whether the issue still persist?

**Comment by Mandiklopper** [comment]
@roberteta please advise if this issue still persist?

**Comment by janwvjaarsveld** [comment]
Stale ticket. Please re-open if this is still an issue
