### ISSUE TITLE
ACCESS/Access for Hospital Maintenance & Leave

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/People-Connect#92]
Please provide access as below to these staff
Olubunmi Nosiru ( A16642) Team Member HCM Operations Employee Services
Ajayi Abayomi Oluwadamilare (A17586) Team Member HCM Operations Payroll
Felix-Michael Lorraine (A16177) Team Member HCM Operations Payroll

Personnel Administration - Hospitals- CMS
All leave pages and views (as per sheet sent by Chidi)- CMS

**Comment by Mandiklopper** [comment]
@chidiif please assist.

**Comment by chidiif** [comment]
Done. @Adebukola, Kindly assist to confirm the users are happy.

**Comment by chidiif** [comment]
Done. @Adebukola, Kindly assist to confirm the users are happy.
