### ISSUE TITLE
EMPLOYEE ARRIVAL NOT PROCESSING AS EXPECTED

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#94]
Employee Arrival loaded and approved for A24257 is yet to be reflected in the Employee screen.

This request was initiated by HRBP Team Member and approved by HRBP Team Lead (Nwamaka Kalu) but the employee is yet to be pushed to the employee or employment contract screen.

**Comment by Mandiklopper** [comment]
https://senseable.co.za/scp/tickets.php?id=207 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
Code has been fixed and this should process now.

**Comment by roberteta** [comment]
Resumption date 04/12/2017  not in sync with Anniversary Date,/Company Entry Date /Site Entry Date of 27/11/2017
The resumption date of the Staff should drive the other dates.

**Comment by Mandiklopper** [comment]
Reopened and assigned to JW.

**Comment by roberteta** [comment]
The following employees loded and approved are also stillon the Arrival screen

1) A24274
2) A24275
3) A24276

**Comment by Mandiklopper** [comment]
Closed.  I checked and did get the employee record and contract.

**Comment by Mandiklopper** [comment]
Assigned to JW on Senseable.

**Comment by Mandiklopper** [comment]
@roberteta , Did the HRBP Supervisor receive the email notification of the 3 employees?  Did they approve al 3 on MSS?

**Comment by roberteta** [comment]
@ Mandi, Yes the HRBP team Lead got notifications and approved all 3 by ckicking the accept link on the email notification.
These staff were still on the Arrival screen when she logged in to PeopleConnect and she again clicked in Offer Accepted and saved. Still these records are still on the Arrival screen, but the Offer Accepted link is greyed out.

**Comment by Mandiklopper** [comment]
Closed.  All 3 employees have now been processed.  Access caused this issue with the acceptance link.  The workflow message has been adjusted to solve this going forward.
