### ISSUE TITLE
Unable to Update Pension fund number & Pension fund administrator  fields on Employee Screen - Others tab

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#98]
Data entered in the Pension Fund number and Pension Fund Administrator fields on the Employee screen  (Others Tab) is clared after being saved and getting the message 'Record Modified'

This issue was reported by HRBP Team Lead - Nwamaka Kalu and confirmed by me on attempts to update these fields.

Please investigate and fix as these information for newly onboarded employees cannot be saved in the system.

**Comment by Mandiklopper** [comment]
https://senseable.co.za/scp/tickets.php?id=208 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
Closed.  Please retest.
