### ISSUE TITLE
Multiple Email Notifications for Staff Movement

### ISSUE THREAD

**Issue by roberteta** [Mandiklopper/People-Connect#99]
Staff, HRBPs and other stakeholders get multiple notifications for the same staff movement as shown below; 

Relief Assignments - 3 email notification each (Event Type - 2 Object & 1 Manual)
Redeployment - 2 notifications each (Event Type -  1 Object & 1 Manual)

Samples of the multiple notifications have been shared with me. Worrkflow Monitor also has multiple notifications

This is cloggig the mailboxes of the affected persons.

Please fix

**Comment by Mandiklopper** [comment]
http://senseable.co.za/scp/tickets.php?id=210 - Not yet assigned on Senseable.

**Comment by Mandiklopper** [comment]
@roberteta according to me this has been closed.  Please confirm.

**Comment by roberteta** [comment]
@Mandiklopper , this has not been resolved. The HRBP Team Lead & Staff got the same notification 3 times for Relief Assignment. See sequence /workflow numbers 
1700013998 /1700009007
1700013400 /1700009009
1300014010 /1700009019

**Comment by jwvjaar** [comment]
Notifications will now only be sent out from the batch task, to prevent the notification from being sent from the object as well as the batch task.
